### ISSUE TITLE
Separate media library page from training materials page

### ISSUE THREAD

**Issue by szymontrocha** [perfsonar/docs#101]
I'm considering separating (new subpage) media library (YT channel, NSRC library) from training materials (slides). It will be more clear as they are now in training materials page which is not convenient and may be dupliacted when new page comes.

**Comment by tonin** [comment]
I support this idea!

**Comment by szymontrocha** [comment]
Done.
I restructured manu and pages now under Learnign and Training Resources: https://www.perfsonar.net/about/training-materials/
