### ISSUE TITLE
Adding bundle installation options

### ISSUE THREAD

**Issue by tonin** [perfsonar/docs#105]
I've prepared a revised slide deck about Installation and Basic Configuration that contains a mention of the bundles and the flowchart to help decide which installation option is best.

It is currently placed in the Working folder in the Google drive: 201710-perfSONAR-2-Installation_and_Basic_Configuration-v5.

To be reviewed and published if ok.

**Comment by szymontrocha** [comment]
Checked and uploaded to web as v5.
