### ISSUE TITLE
pscheduler plot-schedule and normal tasks

### ISSUE THREAD

**Issue by tonin** [perfsonar/docs#106]
[This page](http://docs.perfsonar.net/pscheduler_client_schedule.html#visualizing-the-schedule-with-pscheduler-plot-schedule) says:

> Normal - These are tasks that can run at the same time as other normal and background tasks, but cannot run at the same time as exclusive tasks. Currently there are no examples of these in the default tool set, but the classification is available for those writing new tools.

But when creating a latency test on the CLI, we can actually see tasks in the normal column.  As an example that is showing in the normal column:

```
pscheduler task --repeat PT5M latency --dest mp02
```

**Comment by tonin** [comment]
Example: ![image](https://user-images.githubusercontent.com/484879/33171337-9bcde7e8-d043-11e7-99ad-8cbb767aa1c1.png)

**Comment by mfeit-internet2** [comment]
You're right; `latency` is the sole test in that scheduling class.

```
pscheduler=> SELECT enum, name FROM test JOIN scheduling_class ON scheduling_class.id = test.scheduling_class ORDER BY enum, name;
       enum       |     name     
------------------+--------------
 background       | clock
 background       | dns
 background       | idle
 background       | rtt
 background       | simplestream
 background       | snmpget
 background       | snmpset
 background       | trace
 background-multi | idlebgm
 background-multi | latencybg
 background-multi | snmpgetbgm
 exclusive        | idleex
 exclusive        | throughput
 normal           | latency
```
