### ISSUE TITLE
Ansible port of the toolkit configuration

### ISSUE THREAD

**Issue by brucellino** [perfsonar/docs#108]
Hello, 
I'm working on a few Ansible roles for  the deployment of perfsonar. It should support CentOS and Debian based systems. It seems that the Debian bundle combines the installation and configuration tasks into one, by using dkpg configure triggers. I would like to separate them out, so that the configuration can be handed to Ansible tasks - I want to be able to write  these to respond to the actual that they are deployed in and automate as much as possible. 

In order to do this, I need to understand the configuration tasks - some of the issues I've encountered are described [here](https://github.com/AAROC/perfsonar-base/issues/6)

As far as I can tell the toolkit takes care of the configuration of : 

  1. db
  1. apache
  1. services
  1. firewall 

Can someone provide me please with a pointer to where I should look to understand how these are configured ? I can probably reverse engineer the tasks, but I'm wary of working in the dark like that.

Thanks !
Bruce

**Comment by vvidic** [comment]
On Thu, Jan 11, 2018 at 03:03:27AM -0800, Bruce Becker wrote:
> I'm working on a few Ansible roles for  the deployment of perfsonar.
> It should support CentOS and Debian based systems. It seems that the
> Debian bundle combines the installation and configuration tasks into
> one, by using dkpg configure triggers. I would like to separate them
> out, so that the configuration can be handed to Ansible tasks - I want
> to be able to write  these to respond to the actual that they are
> deployed in and automate as much as possible. 

Both the rpm and deb packages configure their respective services from
postinst scripts.  From the logs it seems that iptables is not working
in the container so it breaks the installation of:

  perfsonar-toolkit-security -> perfsonar-toolkit-systemenv -> perfsonar-toolkit

What container type are you using?


iptables v1.4.14: can't initialize iptables table `filter': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.
dpkg: error processing perfsonar-toolkit-security (--configure):
 subprocess installed post-installation script returned error exit status 255
dpkg: dependency problems prevent configuration of
perfsonar-toolkit-systemenv:
 perfsonar-toolkit-systemenv depends on perfsonar-toolkit-security;
however:
  Package perfsonar-toolkit-security is not configured yet.

dpkg: error processing perfsonar-toolkit-systemenv (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of perfsonar-toolkit:
 perfsonar-toolkit depends on perfsonar-toolkit-systemenv; however:
  Package perfsonar-toolkit-systemenv is not configured yet.

dpkg: error processing perfsonar-toolkit (--configure):
 dependency problems - leaving unconfigured

-- 
Valentin Vidic
Computer Systems Engineer - Expert
Department of Computer Infrastructure and Services
Croatian Academic and Research Network - CARNET
Josipa Marohnica 5, HR-10000 Zagreb, Croatia
tel: +385 1 6661 714, fax. +385 1 6661 635
gsm: +385 91 2480 919
www.CARNet.hr

**Comment by brucellino** [comment]
Hi @vvidic, thanks for the reply. 
> Both the rpm and deb packages configure their respective services from postinst scripts.
this is the "issue" I'm trying to address. I hesitate to call it an issue, since it clearly works for most of the installations of perfsonar, but I want to have a deployment which factors out installation from configuration more explicitly - so having the config done as postinst is not desired in this case. 

> From the logs it seems that iptables is not working in the container 
> ...
> What container type are you using?
I'm testing in a docker environment, against CentOS and Debian Wheezy environments. The description of the default test scenario is here : https://github.com/AAROC/perfsonar-base/blob/master/molecule/default/molecule.yml

My docker is `Docker version 17.09.1-ce, build 19e2cf6` - but I suspect this has more to do with the fact that the containers used to test are not run in priveliged mode.

In any case, the main thing is : 

  ** where can I find the postinst scripts ?** _ie_ where is  the src repo, so that I can try to reproduce the desired final state by implementing it in Ansible.

Thanks ! 
Bruce

**Comment by vvidic** [comment]
On Fri, Jan 12, 2018 at 10:28:05AM +0000, Bruce Becker wrote:
> I'm testing in a docker environment, against CentOS and Debian Wheezy
> environments. The description of the default test scenario is here :
> https://github.com/AAROC/perfsonar-base/blob/master/molecule/default/molecule.yml
> 
> My docker is `Docker version 17.09.1-ce, build 19e2cf6` - but I
> suspect this has more to do with the fact that the containers used to
> test are not run in priveliged mode.

Quite possible, the Debian packages at least have not been tested in
containers so things trying to modify the kernel state like the firewall
might not work correctly.

> In any case, the main thing is : 
> 
>   ** where can I find the postinst scripts ?** _ie_ where is  the src
>   repo, so that I can try to reproduce the desired final state by
>   implementing it in Ansible.

Try to add a source repo using deb-src and download the source using:

  $ apt-get source perfsonar-toolkit

-- 
Valentin Vidic
Computer Systems Engineer - Expert
Department of Computer Infrastructure and Services
Croatian Academic and Research Network - CARNET
Josipa Marohnica 5, HR-10000 Zagreb, Croatia
tel: +385 1 6661 714, fax. +385 1 6661 635
gsm: +385 91 2480 919
www.CARNet.hr

**Comment by brucellino** [comment]
thanks, I'll do that. I think we can close this now 😃
