### ISSUE TITLE
Add missing error message description to pScheduler wiki

### ISSUE THREAD

**Issue by szymontrocha** [perfsonar/docs#109]
Add description of missing error to https://github.com/perfsonar/pscheduler/wiki/Error-Messages:

[psudouser@cowania2 ~]$ pscheduler task throughput --dest 10.1.1.1
Submitting task...
Unable to determine the lead participant: Can't find pScheduler or BWCTL on 10.1.1.1
[psudouser@cowania2 ~]$

**Comment by mfeit-internet2** [comment]
Done.
