### ISSUE TITLE
Examples with IP addresses should include IPv6 examples

### ISSUE THREAD

**Issue by mattzekauskas** [perfsonar/docs#110]
A recent query (yesterday?) about meshconfig (which will be going away) asked if IPv6 addresses need square brackets around them.   The answer was no, for host addresses but yes for read_url and write_urls.  A quick scan of the meshconfig docs showed all examples using IPv4 addresses only.  This case can get fixed during the creation of psconfig docs.

We probably need a task to scan the docs for IP address examples, and ensure there are v6 examples where there are v4, and/or clearly be able to state the rules.

**Comment by szymontrocha** [comment]
@arlake228 is this still an issue for mesh/psconfig? The brackets problem was fixed at earlier release so not sure there are any specific rules necessary?

**Comment by arlake228** [comment]
This is no longer relevant, psconfig handles the bracketing where needed. Closing.
