### ISSUE TITLE
Document the History of perfSONAR

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/docs#112]
Develop a timeline of significant events in the project's history.

Jason Z has a few slides that would be good starting material; he'll get them to me in a few weeks when he's not snowed in.

**Comment by schevali** [comment]
Slides 3-10 courtesy of Szymon:
https://docs.google.com/presentation/d/19w-Yc8F8QGVg4o3h_cLB-b29iSLLWo4gdAgtKXiwD2M/edit#slide=id.p3

**Comment by szymontrocha** [comment]
I uploaded original ppt slide and picture to collaboration drive:
https://drive.google.com/drive/folders/1hxRpKaqgNuPxEgo2GKUB5NzuW-LeIfl-?usp=sharing
Will work now on putting it to website

**Comment by szymontrocha** [comment]
I created a new manu section for this:
https://www.perfsonar.net/about/perfsonar-history-timeline/
which is already filled with infographic and a placeholder for list of events (to be done in the following days).

**Comment by szymontrocha** [comment]
Completed
