### ISSUE TITLE
Add a chapter about migrating toolkit from one host to another

### ISSUE THREAD

**Issue by szymontrocha** [perfsonar/docs#12]
Based on user request:
"I plan to migrate my perfsonarservers  on a new hardware,
 after the 3.5 version is installed and works on my old servers.

Is ther a list of what needs to be copied on the new servers?"

There probably just need to be a migration page added under "Managing the perfSONAR Toolkit” that highlights the important stuff.

**Comment by apertome** [comment]
Related to toolkit/18
