### ISSUE TITLE
Add UMi logo to main web site

### ISSUE THREAD

**Issue by szymontrocha** [perfsonar/docs#138]
perfsonar.net site is currently missing Uni Michigan and still using long IU logo.
This has to be fix in the page template I don't have access to. So by server/CMS admin.

**Comment by szymontrocha** [comment]
per out @perfsonar-training discussion some time ago @mfeit-internet2  / @mattzekauskas  had to investigate a possibility of template modification.

**Comment by mfeit-internet2** [comment]
Sent email to I2 web support.  Ticket number is `2104873683`.

**Comment by mfeit-internet2** [comment]
This will be deployed tonight after 8:00 p.m. EDT.

**Comment by szymontrocha** [comment]
Logo is showing up in the page now.

**Comment by mfeit-internet2** [comment]
This has been done.
