### ISSUE TITLE
Document bwctl depreciation and EOL timeline

### ISSUE THREAD

**Issue by tonin** [perfsonar/docs#145]
We need to announce the BWCTL depreciation and the timeline of the support in the future as described at https://github.com/perfsonar/project/issues/1208#issuecomment-389919668

We need to do that on docs.perfsonar.net but also on http://software.internet2.edu/bwctl/ and probably on https://github.com/perfsonar/bwctl too.

**Comment by arlake228** [comment]
See http://docs.perfsonar.net/release_candidates/4.1b1/manage_update.html#special-upgrade-notes

**Comment by tonin** [comment]
I've also updated https://github.com/perfsonar/bwctl/blob/master/README.md to announce that.

**Comment by tonin** [comment]
We will probably need @mfeit-internet2 or @mattzekauskas to place a notice on this page: https://software.internet2.edu/bwctl/

**Comment by mfeit-internet2** [comment]
Notice added:

IMPORTANT NOTICE

The use of BWCTL became deprecated with the release of pScheduler in perfSONAR 4.0 in April, 2017. While in this deprecated state, the only changes to the program will be those related to security. All other development, maintenance and other support have been permanently discontinued. This documentation remains available for historical purposes only.

**Comment by tonin** [comment]
Thanks, I think that's all then!
