### ISSUE TITLE
Document HTTP Archiver

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/docs#154]
The HTTP archiver isn't represented in the documentation.

**Comment by bgrounds** [comment]
Specifically, the description is wrong:
```
The http archiver sends results to HTTP or HTTPS servers using the POST or PUT operation.

provides the same archiving function as bitbucket but introduces failure and retries a random fraction of the time. This archiver was developed for testing pScheduler and serves no useful function in a production setting.
```
https://docs.perfsonar.net/pscheduler_ref_archivers.html#http

**Comment by mfeit-internet2** [comment]
It sure is.  I'll get that fixed.

**Comment by mfeit-internet2** [comment]
It looks like everything was fine and there were some leftovers from a cut and paste that shouldn't have been there.  The cleaned-up version will appear when we release 4.2.
