### ISSUE TITLE
Note about SELinux for standalone esmond installs

### ISSUE THREAD

**Issue by arlake228** [perfsonar/docs#157]
We should document the info below someplace in case others see a similar issue.

----
It turns out it was an selinux issue.  I’m running enforcing/active and somehow the esmond.log file was impacted after I attempted to migrate the data this morning.  I dug around and found an email from Jon Clausen dated Thurs Sep 14, 2017, 5:56 am and followed the procedure outlined (see below).  It worked – the HTTP 500 errors have stopped.  I’m going to change selinux to permissive and go from there.  How/why this stopped working is still unknown.

Thanks,
George

=============
Hi

Our measurement archive is installed from the CentOS 7 *.iso, with perfSonar
components installed from the internet2 repo.

I chose to leave SELinux active/enforcing, which is actually not causing
many problems, generally - to my pleasant surprise.

The system has yum-cron installed, so updates happen 'whenever'.

Early this morning there were a lot of package updates, and subsequently the
toolkit URL was unable to load test results, showing an 'internal server
error' message instead.

The cause turned out to be a change in SELinux 'type' on a couple of log
files, which resulted in permission denied errors in
/var/log/httpd/error_log

[Thu Sep 14 10:59:19.652856 2017] [:error] [pid 14147] [remote
109.105.99.90:132
] ValueError: Unable to configure handler 'esmond_handler': [Errno 13]
Permission denied: '/var/log/esmond/esmond.log'

The 'cure' would have been to change object type using chcon, or as I did:
move the log file out of the way and restart apache.

The object type change can be seen here:
[jac@psma01 ~]$ ls -Z /var/log/esmond/esmond.log*
-rw-r--r--. apache apache system_u:object_r:httpd_log_t:s0
/var/log/esmond/esmond.log
-rw-r--r--. apache apache system_u:object_r:var_log_t:s0
/var/log/esmond/esmond.log.2017-08-21

This mail is mostly a 'heads up' to other people running the measurement
archive under SELinux, but I guess the info may be relevant to the perfSonar
packagers too.

Should I submit the info somwhere?

br
/jon

**Comment by vvidic** [comment]
On Thu, Oct 04, 2018 at 07:30:28AM -0700, Andrew R. Lake wrote:
> We should document the info below someplace in case others see a similar issue.
> 
> ----
> It turns out it was an selinux issue.  I’m running enforcing/active and somehow the esmond.log file was impacted after I attempted to migrate the data this morning.  I dug around and found an email from Jon Clausen dated Thurs Sep 14, 2017, 5:56 am and followed the procedure outlined (see below).  It worked – the HTTP 500 errors have stopped.  I’m going to change selinux to permissive and go from there.  How/why this stopped working is still unknown.
> 
> Thanks,
> George
> 
> =============
> Hi
> 
> Our measurement archive is installed from the CentOS 7 *.iso, with perfSonar
> components installed from the internet2 repo.
> 
> I chose to leave SELinux active/enforcing, which is actually not causing
> many problems, generally - to my pleasant surprise.
> 
> The system has yum-cron installed, so updates happen 'whenever'.
> 
> Early this morning there were a lot of package updates, and subsequently the
> toolkit URL was unable to load test results, showing an 'internal server
> error' message instead.
> 
> The cause turned out to be a change in SELinux 'type' on a couple of log
> files, which resulted in permission denied errors in
> /var/log/httpd/error_log
> 
> [Thu Sep 14 10:59:19.652856 2017] [:error] [pid 14147] [remote
> 109.105.99.90:132
> ] ValueError: Unable to configure handler 'esmond_handler': [Errno 13]
> Permission denied: '/var/log/esmond/esmond.log'
> 
> The 'cure' would have been to change object type using chcon, or as I did:
> move the log file out of the way and restart apache.
> 
> The object type change can be seen here:
> [jac@psma01 ~]$ ls -Z /var/log/esmond/esmond.log*
> -rw-r--r--. apache apache system_u:object_r:httpd_log_t:s0
> /var/log/esmond/esmond.log
> -rw-r--r--. apache apache system_u:object_r:var_log_t:s0
> /var/log/esmond/esmond.log.2017-08-21

It looks like any update to selinux-policy-targeted would run something like:

  /sbin/restorecon -R /root /var/log /etc/passwd* /etc/group* /etc/*shadow*

This would than revert the whole /var/log including the change we did in
esmond postints:

  chcon -R system_u:object_r:httpd_log_t:s0 /var/log/esmond

It would be better if we could include our changes as an selinux policy
module somehow...

-- 
Valentin Vidic
Computer Systems Engineer - Expert
Department of Computer Infrastructure and Services
Croatian Academic and Research Network - CARNET
Josipa Marohnica 5, HR-10000 Zagreb, Croatia
tel: +385 1 6661 714, fax. +385 1 6661 635
gsm: +385 91 2480 919
www.CARNet.hr

**Comment by vvidic** [comment]
Here goes a PR to make the change persistent so we don't see this issue anymore: https://github.com/esnet/esmond/pull/78

**Comment by szymontrocha** [comment]
@arlake228 is this issue stil in place after Valentin's fix?

**Comment by arlake228** [comment]
Valentin removed need for this, closing
