### ISSUE TITLE
Slide deck cleanup

### ISSUE THREAD

**Issue by schevali** [perfsonar/docs#158]
![image.png](https://images.zenhubusercontent.com/5970c6d961b4ca3b0a752142/c6eec47b-0949-4157-aae8-46f374640163)

Brian Chandler did a recent pass through some training slides and found the following issues:

    * 201801-perfSONAR-2-Installation_and_Basic_Configuration-v5.pdf
    
    - slide 31: badly mangled text overlay
    
    - slides 30-32 and 34 have key parts of text obscured by images
    
    * 201709-perfSONAR-6-Measurement_Tools-v4.pdf
    
    - slide 7 claims the default for command line is iperf2 test, but I'm 
    not sure that's true; testing with between toolkit 4.0.2.2 installations 
    I get iperf3 used as the default 'throughput' test
    
    - slide 11 claims to be an iperf2 test, but the console capture 
    explicitly shows it's using iperf3
    
    - slides 33-36 have not been updated to use pscheduler; they still use 
    bwctl / bwtraceroute
    
    
    Also a trivial broken link in the page 
    https://www.perfsonar.net/resources/training-materials/ps-training/ 
    
    The first link, labelled "perfSONAR Template", points to 
    http://www.perfsonar.net/about/training-materials/2017-07-ps-training/#perfSONAR_Template 
    but that doesn't exist (404).  I think it should just be a relative 
    internal hyperlink to #perfSONAR_Template, which would take you to 
    https://www.perfsonar.net/resources/training-materials/ps-training/#perfSONAR_Template

**Comment by schevali** [comment]
* 201801-perfSONAR-2-Installation_and_Basic_Configuration-v5.pdf
    
    - slide 31: badly mangled text overlay
    
    - slides 30-32 and 34 have key parts of text obscured by images
    
    * 201709-perfSONAR-6-Measurement_Tools-v4.pdf
    
    - slide 7 claims the default for command line is iperf2 test, but I'm 
    not sure that's true; testing with between toolkit 4.0.2.2 installations 
    I get iperf3 used as the default 'throughput' test
    
    - slide 11 claims to be an iperf2 test, but the console capture 
    explicitly shows it's using iperf3
    
    - slides 33-36 have not been updated to use pscheduler; they still use 
    bwctl / bwtraceroute
    
    
    Also a trivial broken link in the page 
    https://www.perfsonar.net/resources/training-materials/ps-training/
    
    The first link, labelled "perfSONAR Template", points to 
    http://www.perfsonar.net/about/training-materials/2017-07-ps-training/#perfSONAR_Template 
    but that doesn't exist (404).  I think it should just be a relative 
    internal hyperlink to #perfSONAR_Template, which would take you to 
    https://www.perfsonar.net/resources/training-materials/ps-training/#perfSONAR_Template

**Comment by szymontrocha** [comment]
I moved things that need reviewing to #153.
All broken links are fixed.
