### ISSUE TITLE
Document additional pscheduler troubleshooting techniques

### ISSUE THREAD

**Issue by apertome** [perfsonar/docs#159]
We need docs on the following:
- [ ] How to find the archive backlog

- [ ] Listing tools that are available. This should go to http://docs.perfsonar.net/pscheduler_ref_tests_tools.html

- [ ] Listing archivers that are available. This should go to http://docs.perfsonar.net/pscheduler_ref_archivers.html

- [ ] The `--reference` field is not documented anywhere I could find (other than `--help`, which is vague)

**Comment by szymontrocha** [comment]
Archivers and tools pages already contain all the information
