### ISSUE TITLE
Documents / Webinars Requests

### ISSUE THREAD

**Issue by schevali** [perfsonar/docs#164]
Quick list from the group of what might be the next items needed to address as Documents and/or Webinars.

- GridFTP (4.2)
- MaDDash advanced options and threshholds
- Troubleshooting example strategies (Diagnosing an issue using pS tools after noticing on a MaDDash)
- Archiving / Elastic, etc. (Getting away from ESmond)
- Troubleshooting pS install/setup issues and errors

**Comment by szymontrocha** [comment]
This was already covered either via cookbooks or due to new release is no loger valid
