### ISSUE TITLE
Fix training resource library page for old materials

### ISSUE THREAD

**Issue by szymontrocha** [perfsonar/docs#166]
This one needs fixing references from the head of the page:
https://www.perfsonar.net/resources/training-materials/201604-ps-training/

Also delete old and possibly unused files which may appear in search like:
https://www.perfsonar.net/media/cms_page_media/1256/20141110-Firewall-PerfWG.pdf

**Comment by szymontrocha** [comment]
I fixed the first issue.
However for the second one this is something different. I don't have access to such location. The CMS provides media library under https://www.perfsonar.net/en/admin/medialibrary/media/... Search doesn't find such file.

**Comment by mattzekauskas** [comment]
sooo, I find it at the bottom of <http://docs.perfsonar.net/manage_security.html>.  If we don't want to reference it we can probably delete the whole paragraph.

I'm a packrat, so I'm less worried about it being available by obscure reference in the CMS.

**Comment by szymontrocha** [comment]
@mattzekauskas did you rather mean https://www.perfsonar.net/deploy/security-considerations/ ? In fact looking at this whole page it can be IMHO deleted from main website as we maintain security info at http://docs.perfsonar.net/manage_security.html (what is refered at the top of aforementioned page). Any objections? I can see if there are things worth moving

**Comment by szymontrocha** [comment]
As an approach to consolidate the training page:
- I moved the content from subpages to https://www.perfsonar.net/resources/training-materials/
- We decided to remove all direct links to slides in favour of Google shared drive
- Old slides references from 4.0.* will be abandoned
- Now all these subpages can be removed:
https://www.perfsonar.net/resources/training-materials/ps-video-library/
https://www.perfsonar.net/resources/training-materials/201604-ps-training/
https://www.perfsonar.net/resources/training-materials/ps-training/
- So far I hided the above from the left menu

**Comment by szymontrocha** [comment]
For the security menu item a redirection was configured (we are not able to edit menu content in CMS) and it now points to http://docs.perfsonar.net/manage_security.html
