### ISSUE TITLE
run-schedule and run-daterange limits text issues

### ISSUE THREAD

**Issue by igarny** [perfsonar/docs#167]
http://docs.perfsonar.net/config_pscheduler_limits.html#run-daterange-check-run-times-against-a-range
This and the paragraph below see multiple issues in the description. 
Most importantly in the end it does not become clear, these are already implemented and operational limits.
Note that limits of this type are not evaluated and will be considered to have passed when determining whether a task will be allowed on the system.

@mfeit-internet2 perhaps Mark can assert

**Comment by mfeit-internet2** [comment]
That limit was implemented in the first release.

Limits involving time are only evaluated only when scheduling runs.  They're ignored when the task is submitted and will result in non-starters as the scheduler tries to schedule runs.

**Comment by szymontrocha** [comment]
There is nothing to update
