### ISSUE TITLE
Make current perfSONAR version obvious in the web sites

### ISSUE THREAD

**Issue by szymontrocha** [perfsonar/docs#170]
Some users were reporting to me that it's not obvious to see what is the current pS version available. This is not immediately seen in the wen sites. In docs you either need to go to subpage and then download ISO to see it, on the main web site even more difficult.
It makes sense to:
- [x] in www.perfsonar.net make sure top of the announcements is the one with lates version/fix available
- [x] in docs add something in the main page (and probably in download page too) to indicate it clearly

**Comment by tonin** [comment]
Related to that, I think that having a clear **changelog** page would also help to see the differences between versions.  This changelog page could just be links to the past release notes.

**Comment by szymontrocha** [comment]
I fixed the version issue in www.perfsonar.net
For the changelog request I'm creating a separate issue #181

**Comment by szymontrocha** [comment]
I added the version and release infomation to documentation pages (main and downloads)
