### ISSUE TITLE
Document how to use task priority

### ISSUE THREAD

**Issue by arlake228** [perfsonar/docs#176]
We need documentation on task priority. Not sure exactly how should this look, but including it here so we track.

**Comment by mfeit-internet2** [comment]
Is [what's in the 4.2.0 branch](https://github.com/perfsonar/docs/blob/4.2.0/config_pscheduler_limits.rst#priorities-which-runs-happen-and-which-do-not) not sufficient?

**Comment by arlake228** [comment]
content is good, but it should be on docs.perfsonar.net. We may also want to provide some CLI and psconfig examples somewhere.
