### ISSUE TITLE
Have a changelog page

### ISSUE THREAD

**Issue by szymontrocha** [perfsonar/docs#181]
Antoine requested that having a clear changelog page would also help to see the differences between versions. This changelog page could just be links to the past release notes.

**Comment by szymontrocha** [comment]
Antoine, can you elaborate a bit more? Or give an example how this should look like? We are not sure what the request is.

**Comment by tonin** [comment]
Actually, I think the page at https://www.perfsonar.net/release-notes/ covers that request.  Not sure if that page was already existing at the time I asked for this request.

The only thing that might be missing is a link to that page from the docs.perfsonar.net website, probably in the [Previous Releases](https://docs.perfsonar.net/#previous-releases) section.  With a link that would read something like "Current and past release notes" or similar.
