### ISSUE TITLE
Move perfSONAR main website to a new CMS

### ISSUE THREAD

**Issue by szymontrocha** [perfsonar/docs#185]
This is an issue to track all activities related to this change.

**Comment by mfeit-internet2** [comment]
Internet2 already provides a production-supported system for our web site and can provide one for whatever we come up with.  I can also provide a VM on our development farm for experimentation and evaluation.

I would recommend that we evaluate Drupal as a potential replacement.

**Comment by szymontrocha** [comment]
This is definitely resolved by @mfeit-internet2 . Site moved to https://github.com/perfsonar/website
