### ISSUE TITLE
Verify and update "Determining Who Is Testing to Your Host" section

### ISSUE THREAD

**Issue by szymontrocha** [perfsonar/docs#19]
Currently this section http://docs.perfsonar.net/release_candidates/4.0rc1/manage_logs.html#determining-who-is-testing-to-your-host describes the process which is using some old references. It's not sure the script is still working as expected and how it should present data in 4.0. It needs verification of the script usage by developers and then section update. It may be related to perfsonar/toolkit#14

**Comment by schevali** [comment]
Mark said he needs to make a tiny program to pull the data from the API

**Comment by schevali** [comment]
Then a short description of how to run it

**Comment by bltierney** [comment]
looks like this is now complete, so closing.
