### ISSUE TITLE
Better document numeric types in meshconfig

### ISSUE THREAD

**Issue by arlake228** [perfsonar/docs#20]
From Soichi:

> Lastly, the documentation doesn't explain if numeric fields can be integer or decimal (and if decimal, number of acceptable precision). For example, it looks like bucket_width/packet_interval can be decimal, but sample_count is an integer? If you could add more specific numeric specification, I can add appropriate validations on the UI to prevent user from entering invalid numbers.

**Comment by soichih** [comment]
@arlake228 

Sorry, I think you've answered this somewhere - but what does NUMBER mean again (was it just an integer, or can it be decimals?) 

Also, I am looking at this
> http://docs.perfsonar.net/release_candidates/4.0rc2/config_mesh.html
```
Description:	The rate at which the tool will attempt to send TCP packets. Can specify as bits per second or with suffix K, M, or G to indicated Kbps, Mbps or Gbps respectively.
Syntax:	tcp_bandwidth NUMBER
```
Although it says it's NUMBER, the actual value won't be number if you are allowing suffix (like "10G") Is this field really a string then? Looking at "window_size", I think it default to "bytes" if it's number, but user could specify "10M" and the field becomes a string.. Does tcp_bandwidth default to *bytes* also?

**Comment by arlake228** [comment]
Replaced by psconfig. Everything in psconfig has a schema file, this will not be issue.
