### ISSUE TITLE
FAQ entry about resetting a failing Cassandra

### ISSUE THREAD

**Issue by laeti-tia** [perfsonar/docs#201]
While we're still using Cassandra, it might be useful to add the [details of this list post](https://lists.internet2.edu/sympa/arc/perfsonar-user/2019-11/msg00009.html) as a FAQ entry when people have a failing Cassandra that cannot recover (i.e. Cassandra won't start or quit quickly after start).

The instructions are:
```
systemctl stop cassandra
systemctl stop httpd
pkill -9 -f java
cd /var/lib/cassandra/data/system/local/
```
Move the last Cassandra DB file, something like `system-local-jb-xyz-Data.db` to a temporary directory (just in case).  Then
```
systemctl start cassandra
systemctl start httpd
```
Or
```
init 0
init 6
```

**Comment by szymontrocha** [comment]
This method will result in some data loss. Do we still recommend this with an appropriate warning?

**Comment by szymontrocha** [comment]
With latest release based on Opensearch this issue is no longer valid
