### ISSUE TITLE
Improvement of the release notes

### ISSUE THREAD

**Issue by igarny** [perfsonar/docs#204]
This one comes from a GN partner very much annoyed about some issues with changed pS configuration files or actually (more precisely put) the miss on changing / improving their configuration files.

“I have problems to find which files get changed by a Perfsonar install/update or psconfig. ”

The issue was between 4.2.1 and 4.2.2 and the limits.conf file.
Anyway after a consultation with @tonin we could potentially list all changed configuration files in a list with every release note.

**Comment by igarny** [comment]
Actually I found this:
https://www.perfsonar.net/release-notes/version-4-2-2/

Perhaps there is still room for improvement, though

**Comment by szymontrocha** [comment]
All release notes are available at https://www.perfsonar.net/docs_releasenotes.html
I rephrased the reference in http://docs.perfsonar.net/previous_releases.html
