### ISSUE TITLE
Add path for running ps_remove_data script

### ISSUE THREAD

**Issue by apertome** [perfsonar/docs#212]
In this section:

https://docs.perfsonar.net/multi_ma_backups.html#using-ps-remove-data-py

It says to run 
```
. bin/activate
python /usr/lib/esmond/util/ps_remove_data.py -c usr/lib/esmond/util/ps_remove_data.conf
```

But it doesn't specify where you should be when you run that. I think it's `/usr/lib/esmond`, but I'm not 100% sure

**Comment by apertome** [comment]
It would also probably help people to document the script parameters

**Comment by szymontrocha** [comment]
In fact this section needs a bit of rewritting. The script itself was extended with a umbrella shell script `/usr/lib/perfsonar/scripts/clean_esmond_db.sh` that can directly be used by CLI or cron. But documentation left unchanged. Assigning to myself to update.

This page may also need update as a result: https://docs.perfsonar.net/config_files.html
