### ISSUE TITLE
Example of JQ transform to skip local archiving

### ISSUE THREAD

**Issue by laeti-tia** [perfsonar/docs#221]
In the PMP mesh, we wanted to have mesh measurement data only be stored remotely on the central PMP server and not having a local copy on the pS node as is the default setup with any toolkit host.  This is possible through the use of a custom JQ transform to be added to the pSConfig local archiving definition.

In the `/etc/perfsonar/psconfig/archives.d/esmond_local.json` file, which is created at installation time on any toolkit host, you can add a JQ transform that will return `null` when a reference is set in tasks specification, for example:

```
{
    "archiver" : "esmond",
    "data" : {
        "url" : "https://{% scheduled_by_address %}/esmond/perfsonar/archive/",
        "measurement-agent" : "{% scheduled_by_address %}",
        "_auth-token" : "*****"
    },
    "transform": {
            "script": "if (.task.reference.\"pmp-measurement\" == true) then null else . end"
    }
}
```

If you have on your central JSON file a task specification like the following:
```
"pSmall_IPv4_loss": {
    "_meta": {
    "display-name": "IPv4 OWD"
    },
    "reference": {
        "pmp-measurement": true
    },
    "group": "grp_lat_4",
    "test": "tst_owd_4"
},
```

Then all the measurements resulting from this task will not be stored locally on the pS toolkit host.

The addition to the `esmond_local.json` needs to be replicated on all pS node where you want to avoid local storage of the central measurements.  This can easily be done through some Ansible automation for example.

**Comment by tonin** [comment]
We probably need to define or add a place in the current docs website where we can put such examples.  Or just make it part of the regular docs flow?

**Comment by arlake228** [comment]
We should add instructions for doing this here: https://docs.perfsonar.net/psconfig_templates_advanced.html

**Comment by mfeit-internet2** [comment]
This is a function of pScheduler rather than pSConfig and is covered here:  https://docs.perfsonar.net/pscheduler_ref_archivers.html#transforms

> If the script returns a JSON value of `null`, pScheduler will discard the result and not pass it to the plugin. Because the transformation happens within pScheduler before any plugin code is invoked, this mechanism is a very efficient way to filter results and is preferred over writing custom plugins.
