### ISSUE TITLE
FAQ entry about graphs failing to load when using remote esmond

### ISSUE THREAD

**Issue by laeti-tia** [perfsonar/docs#233]
When a MaDDash setup uses data from some remote esmond archive, the graphs can appear empty although there actually is data present.  One cause of such a failure can be using a self-signed certificate on the remote esmond archive  (the default perfSONAR toolkit setup).  This error can be difficult to troubleshoot because no security warning nor any other error shows up clearly, it's just the graph page that doesn't show any data.

There are 2 workarounds to fix that:
- install a full SSL certificate on the remote esmond/toolkit, which will solve this issue for all MaDDash users, the certificate then needs to be kept up to date ;
- manually go to the esmond/toolkit page and individually accept the self-signed certificate, this procedure needs to be done by every user.

Properly resolving this issue is discussed in 2 different places:
- short term mitigation in the graphs themselves: https://github.com/perfsonar/graphs/issues/191
- long-term solution in using Let's Encrypt on the toolkit (but only a solution for a host having Internet access): https://github.com/perfsonar/toolkit/issues/305

**Comment by szymontrocha** [comment]
With latest release based on Opensearch this issue is no longer valid
