### ISSUE TITLE
Add mention of PostgreSQL password prompt

### ISSUE THREAD

**Issue by laeti-tia** [perfsonar/docs#235]
When installing pScheduler on Debian and Ubuntu with a regular `apt install` the user is prompted to enter a password for the new PostgreSQL database created.  The user can choose this password arbitrarily or even leave it empty (the DB is only accessible locally).

We should document that and even tell that APT installation can be done in non-interactive mode to avoid the prompt altogether (this is what the Ansible roles we provide are doing).  This can be done by setting the following environment variable when installing: `DEBIAN_FRONTEND=noninteractive apt install perfsonar-toolkit`

**Comment by szymontrocha** [comment]
@laeti-tia what about adding the following note to the description of Debian bundle installation process:

Setting the default user password in PostgreSQL
++++++++++++++++++
During installation, with a regular _apt install_ the user is prompted to enter a password for the new PostgreSQL database created. You can choose this password arbitrarily or leave it empty (the DB is only accessible locally). 
If you install packages with APT in non-interactive mode to avoid the password prompt set the following environment variable when installing: _DEBIAN_FRONTEND=noninteractive apt install perfsonar-toolkit_

**Comment by laeti-tia** [comment]
Looks good to me (I made a few changes to make it clearer).
