### ISSUE TITLE
Be clear that python27 virtualenv is only needed on centOS 6

### ISSUE THREAD

**Issue by arlake228** [perfsonar/docs#24]
A few places we have steps like the following:

```
source /opt/rh/python27/enable
/opt/rh/python27/root/usr/bin/virtualenv --prompt="(esmond)" .
. bin/activate
```
Those are only needed on CentOS 6 (not CentOS 7), we should indicate as much.

**Comment by arlake228** [comment]
Actually to clarif, you still need to run: `. bin/activate`

**Comment by tonin** [comment]
On the Debian port, we have a script in `/usr/share/esmond/esmond_manage` that is used to encapsulate those commands.  Shouldn't we do the same for CentOS and then adapt the script commands to each OS?

**Comment by tonin** [comment]
The documentation on http://docs.perfsonar.net/release_candidates/4.0rc2/multi_ma_install.html (for example), also need to be adapted to Debian/Ubuntu setup.

**Comment by szymontrocha** [comment]
@tonin - we need some information what has to be adapted and how to Debian
