### ISSUE TITLE
Update Toolkit screenshots with Grafana UI

### ISSUE THREAD

**Issue by arlake228** [perfsonar/docs#249]
There are a few places in the docs we have screenshots of the old interface. Most of our screenshots center around the config GUI that hasn't changed, so there is not too many. Below is the list i found so far:

- [x] https://docs.perfsonar.net/release_candidates/5.1.0/install_quick_start.html - Step #6, Step #15
- [x] https://docs.perfsonar.net/release_candidates/5.1.0/install_config_first_time.html - Under "Accessing the Web Interface" and "Updating Your Administrative Information"
- [x] https://docs.perfsonar.net/release_candidates/5.1.0/manage_admin_info.html - One at the top
- [x] https://docs.perfsonar.net/release_candidates/5.1.0/manage_ntp.html we should probably delete this page since UI dropped. Already have an NTP overview page.
- [x] Remove section https://docs.perfsonar.net/release_candidates/5.1.0/manage_logs.html#accessing-log-files-through-the-web-interface since this is not a thing anymore
- [x] Delete entire page https://docs.perfsonar.net/release_candidates/5.1.0/using_ext_tools.html

**Comment by szymontrocha** [comment]
- [ ] https://docs.perfsonar.net/release_candidates/5.1.0/manage_update.html#managing-automatic-updates-from-the-toolkit-web-interface - pt. 2 Configuration button screenshot

**Comment by szymontrocha** [comment]
Did most of this. Few pics of a plain main Grafana page still missing as i can't reinstall latest 5.1 due to issue with the repo. Will do as soon as it is available
I'm not sure we should delete NTP config page. This part of GUI still remains...
