### ISSUE TITLE
Debian: Update the auto-updates setup and configuration

### ISSUE THREAD

**Issue by tonin** [perfsonar/docs#28]
Some changes happened in https://github.com/perfsonar/toolkit/issues/157 that needs to be reflected in the documentation.

**Comment by tonin** [comment]
We'll also need to mention in the release note that the upgrade path from 3.5 to 4.0 on Debian/Ubuntu is manual.  People will need to change their apt source files.

**Comment by szymontrocha** [comment]
Added a note to RC1 release notes as this is from the beginning. Documentation steps are tracked in #36

**Comment by tonin** [comment]
@szymontrocha Will the final release notes be the sum of release notes from RC1+RC2+RC3?

**Comment by szymontrocha** [comment]
I think so. But RCs notes are incremental
