### ISSUE TITLE
condense section Using and Interpreting perfSONAR

### ISSUE THREAD

**Issue by szymontrocha** [perfsonar/docs#31]
Sections:

- [x] http://www.perfsonar.net/use/navigating-toolkit-interface/
- [x] http://www.perfsonar.net/use/running-measurement-tools/
- [x] http://www.perfsonar.net/use/interpresting-grapphs-and-data/
are old aand could be condensed. Refer instead for all details to docs.perfsonar.net. Here just some statements and pointers to docs.perfsonar.net.

**Comment by bltierney** [comment]
I think I finished this, but needs review.

Note that a couple of the links are broken until http://docs.perfsonar.net/release_candidates/4.0rc3 gets renamed to http://docs.perfsonar.net/

**Comment by szymontrocha** [comment]
The three subpages are now condensed to http://www.perfsonar.net/use/ with links do doc.perfsonar.net. I fixed link description and some wording. Looks good now.
