### ISSUE TITLE
Delete security consideration page

### ISSUE THREAD

**Issue by szymontrocha** [perfsonar/docs#32]
Delete http://www.perfsonar.net/deploy/security-considerations/ . Review if there are parts to be moved to docs. Keep all firewall details in docs.perfsonar.net.

**Comment by bltierney** [comment]
I created this: http://docs.perfsonar.net/release_candidates/4.0rc3/manage_security.html

And removed much of the material on that page. Please review, and close this if you think its OK now.

**Comment by bltierney** [comment]
make sure all important iptables / firewalld stuff is added.

**Comment by bltierney** [comment]
mostly overlaps with #52, so closing
