### ISSUE TITLE
update low cost and deployment examples

### ISSUE THREAD

**Issue by szymontrocha** [perfsonar/docs#34]
- [x] http://www.perfsonar.net/deploy/hardware-selection/low-cost-hardware/
- [x] http://www.perfsonar.net/deploy/hardware-selection/deployment-examples/

should reflect the current status and knowledge including GEANT small nodes deployment

**Comment by bltierney** [comment]
IMHO, this material should move to docs.perfsonar.net

**Comment by bltierney** [comment]
I created a rst file for this purpose. See: install_small_node_details

Also, I think it would be good to link in the small node paper, and summarize it on that page.

**Comment by schevali** [comment]
These pages need to be updated as well:

http://docs.perfsonar.net/release_candidates/4.0rc2/low_cost_nodes.html
http://docs.perfsonar.net/release_candidates/4.0rc2/low_cost_nodes_configuration.html

Closed #25 as a duplicate

**Comment by szymontrocha** [comment]
I think this needs a bit of clarification. For now I see three pages:

- https://github.com/perfsonar/docs/blob/4.0rc2/install_low_cost_nodes.rst (main page leads to it)
- https://github.com/perfsonar/docs/blob/4.0rc2/install_small_node_details.rst (http://docs.perfsonar.net/release_candidates/4.0rc2/install_hardware.rst leads to it)
- https://github.com/perfsonar/docs/blob/4.0rc2/low_cost_nodes_configuration.rst

Apart from different naming convention I'm not sure the idea between the first two pages which may just be a mistake?

**Comment by bltierney** [comment]
yeah, that was a mistake, and needs to be cleaned up/merged

**Comment by schevali** [comment]
http://docs.perfsonar.net/release_candidates/4.0rc2/install_small_node_details.html is currently linked up from Ye Olde www.perf page(s).

https://github.com/perfsonar/docs/blob/4.0rc2/low_cost_nodes_configuration.rst is populated, but without much of actual current use.

**Comment by szymontrocha** [comment]
Let's summarise. We have three pages now:

1. http://docs.perfsonar.net/release_candidates/4.0rc3/install_small_node_details.html
2. http://docs.perfsonar.net/release_candidates/4.0rc3/install_low_cost_nodes.html
3. http://docs.perfsonar.net/release_candidates/4.0rc3/low_cost_nodes_configuration.html 

However I can't figure out where they are linked from - seems like there is no menu item for this. I think (1) can be deleted as a separate page and be a subsection of (2).
Both pages from www.perfsonar.net were removed.

**Comment by bltierney** [comment]
How about all those get combined and added to:

http://docs.perfsonar.net/release_candidates/4.0rc3/install_small_node_details.html

which is linked from: http://docs.perfsonar.net/release_candidates/4.0rc3/install_hardware.html

The info on low_cost_nodes_configuration.html is really out of date, and maybe should just be removed?

**Comment by szymontrocha** [comment]
I combined install_small_node_details with install_low_cost_nodes content and removed the latter page.
http://docs.perfsonar.net/release_candidates/4.0rc3/install_small_node_details.html needs review as we mention some script there (not sure it works for the latest release). If it's no longer the case also low_cost_nodes_configuration can be removed. I think install_small_node_details is also centered about ARM based nodes and while our GEANT setup shows the nodes are able to run full toolkit still being small and low cost.

**Comment by bltierney** [comment]
I dont think we need to mention the setup_debian_testpoint.sh. But if so, it needs to be updated to include pScheduler.

**Comment by schevali** [comment]
Yesterday updated the Master branch (current) and rc3 branch pages to inlude expanded information on small nodes and suggested minimum requirements. Segregated the information into three categories: pi-class, ~$200, and cheap 1RU devices.

Removed the outdated small node script text as suggested.

"For installation of Ubuntu from a standard ISO, there is also a script to help autoconfigure the perfsonar repositories and get the required software setup. See the :doc:`low cost nodes configuration <low_cost_nodes_configuration>` section for more information."

Looks like all the low_cost pages have been condensed into this final page currently: https://github.com/perfsonar/docs/blob/4.0rc3/install_small_node_details.rst 

Interested in feedback on adding links to the small nodes testbed and even ganglia here for interested parties at the end of the document under Additional Information. Thoughts?

**Comment by szymontrocha** [comment]
I fixed a few typos and other small things in the doc plus removed further references to the script. I also created a separate section in the main page to separate topics related to requirements and other preparation including small nodes. Removed http://docs.perfsonar.net/release_candidates/4.0rc3/low_cost_nodes_configuration.html as no longer used.

**Comment by schevali** [comment]
Committed another pass of the small nodes section.

**Comment by schevali** [comment]
Commented in the Deployment page ticket already, but I have a section for the end of that page detailing the current models in the works.

**Comment by bltierney** [comment]
this all looks good to me now, so closing. Feel free to reopen if you disagree.
