### ISSUE TITLE
Document new meshconfig options

### ISSUE THREAD

**Issue by arlake228** [perfsonar/docs#35]
Add the following to meshconfig docs:

- [ ] Document `reference` parameter
- [ ] Document `created_by` parameter
- [ ] Document `configure_archives` at test level
- [ ] Document how multiple archives are handled
- [ ] Document simplestream test
- [ ] Document that guiagent can now do traceroute and ping tests

**Comment by schevali** [comment]
Document .json auto-generation/daemon usage

**Comment by schevali** [comment]
/usr/lib/perfsonar/bin/build_json -o /var/www/html/destination_mesh_config.json source_mesh_config.conf

**Comment by arlake228** [comment]
Replaced by pSConfig
