### ISSUE TITLE
Debian/Ubuntu specific documentation

### ISSUE THREAD

**Issue by tonin** [perfsonar/docs#36]
Most of the CLI related documentation we have needs to be reviewed in light of a Debian or Ubuntu installation.  Let's track all the needed changes here.

Installation:
- [ ] add a Debian toolkit installation option in http://docs.perfsonar.net/release_candidates/4.0rc2/install_toolkit.html
- [x] add a Debian MaDDash installation option in http://docs.perfsonar.net/release_candidates/4.0rc2/manage_extra_tools.html#maddash

File locations:
- [x] double check the path to logfiles on http://docs.perfsonar.net/release_candidates/4.0rc2/manage_logs.html

Updates:
- [x] list Debian manual auto-update documentation on http://docs.perfsonar.net/release_candidates/4.0rc2/manage_update.html  See also https://github.com/perfsonar/docs/issues/28

Central Server management:
- [x] http://docs.perfsonar.net/release_candidates/4.0rc2/mca_install.html#debian
- [x] http://docs.perfsonar.net/release_candidates/4.0rc2/multi_ma_install.html
- [x] http://docs.perfsonar.net/release_candidates/4.0rc2/multi_ma_clustering.html
- [x] http://docs.perfsonar.net/release_candidates/4.0rc2/multi_ma_backups.html
- [x] http://docs.perfsonar.net/release_candidates/4.0rc2/multi_logging.html

Puppet for Debian?

- [x] http://docs.perfsonar.net/release_candidates/4.0rc2/multi_puppet_install.html

We should double check the config files list:
- [x] http://docs.perfsonar.net/release_candidates/4.0rc2/config_files.html
- [x] and probably all that is part of the **Configuration Reference** section

Example of changes needed:
- [x] `/sbin/service` is `/usr/sbin/service` on Debian, but maybe we can refer to the command as `service` only.

**Comment by szymontrocha** [comment]
I made a few changes with 1c35999447adc995f654eee87cdf62389748324b but I'm not able to fix most of the rest as I don't know the packaging details and also somebody who setup Debian-based central MA/multi MA would have to describe the central mgmt part. I don't have such deployment.

**Comment by vvidic** [comment]
Don't think Puppet would work on Debian at the moment. Some of it is specific to RHEL6 and probably to a certain Puppet version. The recipes should probably be updated for RHEL7 and selected Debian/Ubuntu versions.

**Comment by vvidic** [comment]
Replaced ``/sbin/service`` calls with ``service`` assuming everything is run as root.

**Comment by vvidic** [comment]
MCA is not packaged for Debian (NodeJS issues), so not sure if we can document anything there?

**Comment by vvidic** [comment]
Did not find anything Debian specific in the Configuration Reference pages.

**Comment by tonin** [comment]
All Debian information should be up to date at this point.
