### ISSUE TITLE
user: reference epel-release-7-9.noarch.rpm as 7-8 no longer exists 

### ISSUE THREAD

**Issue by igarny** [perfsonar/docs#38]
http://docs.perfsonar.net/release_candidates/4.0rc1/install_centos.html 
You should reference epel-release-7-9.noarch.rpm as 7-8 no longer exists it seems

```
From: perfsonar-user-request@internet2.edu [mailto:perfsonar-user-request@internet2.edu] On Behalf Of Daniel Spisak
Sent: Mittwoch, 15. Februar 2017 04:39
To: perfsonar-user@internet2.edu
Subject: [perfsonar-user] Questions about perfsonar 4

```

**Comment by tonin** [comment]
This had already been corrected in the 4.0RC2 release docs where we use the link to the latest EPEL release.
