### ISSUE TITLE
mention what services should be running on a central management server

### ISSUE THREAD

**Issue by igarny** [perfsonar/docs#39]
http://docs.perfsonar.net/release_candidates/4.0rc1/install_centos.html 
Under Step 7, starting services there is no mention of what services should be running on a central management server

```
From: perfsonar-user-request@internet2.edu [mailto:perfsonar-user-request@internet2.edu] On Behalf Of Daniel Spisak
Sent: Mittwoch, 15. Februar 2017 04:39
To: perfsonar-user@internet2.edu
Subject: [perfsonar-user] Questions about perfsonar 4

```

**Comment by igarny** [comment]
Most likely this is not the correct place also for the information required. Certainly "install_centos.html" should be strictly related to CentOS deployments, but we also have Debian to consider.

**Comment by szymontrocha** [comment]
Agree this has to be clarified. Step 8 is just an example with main sentence saying "You can start all the services by rebooting the host since all are configured to run by default". Probably reference to other place like extended manage_services.html#list-of-services will work.

**Comment by tonin** [comment]
BTW, the most up to date version of the docs is at http://docs.perfsonar.net/release_candidates/4.0rc2/install_centos.html

**Comment by bltierney** [comment]
I started working on this. See: http://docs.perfsonar.net/release_candidates/4.0rc2/manage_daemons.html

Needs more work tho.

**Comment by schevali** [comment]
Add clickable links to each daemon for descriptions of what each service does.

Table presentation?

Clarify text to make sure it is understood that all testpoint daemons are also part of Toolkit (but not the other way around)

**Comment by szymontrocha** [comment]
This RC page was not brought into live so worth coming back to it. I will look at it.
