### ISSUE TITLE
Full HA example of MA

### ISSUE THREAD

**Issue by arlake228** [perfsonar/docs#4]
It would be nice to add an example of a fully redundant, load balanced measurement archive to the clustering page. Right now it does a survey of the various options, but a single example would be good. The example should include:
- A topology with 2 load balancers, two httpd servers running esmond, 2 cassandra servers and 2 PostgreSQL servers. Alternatively you could just have two load balancers and two more servers running everything else.
- Setup a cassandra cluster
- Create a master slave setup with postgreSQL with automatic failover (possibly using the load balancers)
- Setup two web servers with esmond, both pointing at the clusters above
- Setup two load balancers with HAProxy and keepalived
- Optionally install HAproxy on each web server and use it to detect cassandra failures better. pycassa relies on timeouts, HAProxy would remove from the pool entirely. Note we would run this client side, not on cassandra servers

**Comment by szymontrocha** [comment]
WIth the new Opensearch archive this isuue in no loger valid
