### ISSUE TITLE
Add pscheduler error message guide (and other components too)

### ISSUE THREAD

**Issue by schevali** [perfsonar/docs#43]
Work with Devs to populate a list of error messages from the various logs with next step suggestions.

**Comment by schevali** [comment]
Creating a starting page and will assist additionally by populating with errrors/messages separated by .log file

**Comment by mfeit-internet2** [comment]
Suggest digging through the sources for error messages.

**Comment by schevali** [comment]
Scott's going to create this page and a template at layout.

Then Mark is going to programmatically dump the possible error messages from the tools for population and suggested investigation/fixes.

Then "Help Wanted" for anyone else to tag in to help populate help txt

**Comment by mfeit-internet2** [comment]
First cut is here:  https://github.com/perfsonar/pscheduler/wiki/Error-Messages

**Comment by bltierney** [comment]
linked from troubleshooting page. closing
