### ISSUE TITLE
update hardware requirements page

### ISSUE THREAD

**Issue by bltierney** [perfsonar/docs#44]
This page is very out of date for 4.0, and needs to be updated before the release:

http://www.perfsonar.net/deploy/hardware-selection/hardware-advice/

**Comment by bltierney** [comment]
This material should be moved to docs.perfsonar.net, and just be a link from www.perfsonar.net

The new page on docs.perfsonar.net should say:

4 cores required for all use cases
4GB Ram for 'testpoint' bundle, 8GB for other bundles.

**Comment by bltierney** [comment]
new pages on docs.perfsonar.net are now ready:

http://docs.perfsonar.net/release_candidates/4.0rc2/install_hardware.html

**Comment by mfeit-internet2** [comment]
Almost the same as #45
