### ISSUE TITLE
delete hardware pages from www.perfsonar.net, and link to docs.perfsonar.net

### ISSUE THREAD

**Issue by bltierney** [perfsonar/docs#45]
These pages have now been migrated to docs, and should be removed and just linked from www.perfsonar.net:

- [x] https://www.perfsonar.net/deploy/hardware-selection/  is now: http://docs.perfsonar.net/release_candidates/4.0rc2/install_hardware.html
- [x] https://www.perfsonar.net/deploy/hardware-selection/hardware-advice/ is now: http://docs.perfsonar.net/release_candidates/4.0rc2/install_hardware_details.html
- [x] https://www.perfsonar.net/deploy/hardware-selection/virtual-machines/ is now: http://docs.perfsonar.net/release_candidates/4.0rc2/install_virtual_machine_details.html

**Comment by szymontrocha** [comment]
This was done for RC2. The change now is as following:
https://www.perfsonar.net/deploy/hardware-selection/ is showing a list of topics:
- Hardware Requirements -> http://docs.perfsonar.net/release_candidates/4.0rc2/install_hardware.html
- perfSONAR on a Virtual Machine -> http://docs.perfsonar.net/release_candidates/4.0rc2/install_virtual_machine_details.html
- perfSONAR on a Low Cost Nodes -> http://docs.perfsonar.net/release_candidates/4.0rc2/install_small_node_details.html
**These links however have to be modified when RC code is published as master.**

There are still headers leading to:
- Number of perfSONAR Servers -> http://www.perfsonar.net/deploy/hardware-selection/server-count/
- Example Deployments ->http://www.perfsonar.net/deploy/hardware-selection/deployment-examples/
What should we do with them?

The menu topic https://www.perfsonar.net/deploy/hardware-selection/ doesn't show now subtopics. I hidden the pages from site until it's decided if some contents has to be moved or completely deleted. (see also #34 ).

**Comment by bltierney** [comment]
I think those pages should be migrated to docs.perfsonar.net too.

**Comment by bltierney** [comment]
they probably need some updating too...

**Comment by bltierney** [comment]
pretty sure this is now complete, so closing.
