### ISSUE TITLE
general updates for www.perfsonar.net

### ISSUE THREAD

**Issue by bltierney** [perfsonar/docs#46]
Many pages need a quick update pass remove outdated material.

A few example of pages that need updates are:
- [x]     http://www.perfsonar.net/project-information/project-roadmap/ - update dates
- [x]    http://www.perfsonar.net/about/who-is-uisng/ - now up to 2100 hosts.
- [x]   https://www.perfsonar.net/release-notes/ - link to 4.0 stuff

and probably much more.

Should do other issues related to www.perfsonar.net first, as that will reduce the number of pages to check.

**Comment by bltierney** [comment]
I made a quick update to https://www.perfsonar.net/about/who-is-uisng/   More is needed tho.

**Comment by bltierney** [comment]
http://www.perfsonar.net/project-information/project-roadmap/ updated, but others should review.

**Comment by tonin** [comment]
For the map on https://www.perfsonar.net/about/who-is-uisng/ here is a better/newer capture.  But I don't have access to the CMS to upload it.  Who can do that?


![ps-world-map](https://cloud.githubusercontent.com/assets/484879/24157857/7f30855e-0e52-11e7-8c70-22cd80ab909c.png)

**Comment by bltierney** [comment]
Szymon, Scott and I all have access now. One of us will do this.

**Comment by szymontrocha** [comment]
I updated the picture and some small corrections, and added links to 4.0 RC notes. Roadmap description is fine for me.
