### ISSUE TITLE
Document Simplestreamer

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/docs#47]
The `simplestreamer` tool uses incoming TCP ports 10000-10010.  This needs to be added to the docs.

**Comment by bltierney** [comment]
simplestreamer itself needs to be documented too, along with
http://www.perfsonar.net/deploy/security-considerations/#Using_perfSONAR_with_Firewalls

**Comment by bltierney** [comment]
any reason this needs its own ports? Could it use the iperf2 port range?

**Comment by mfeit-internet2** [comment]
Simplestream is background-scheduled, which means it could pick ports used by iperf2.  As it is, multiple instances running at the same time could collide because the ports are selected at random.

I'd be amenable to hacking off a chunk of the iperf2 port range and altering simplestreamer to use that.

**Comment by bltierney** [comment]
The docs now say ports 5890-5900

see: http://docs.perfsonar.net/release_candidates/4.0rc3/manage_security.html

**Comment by mfeit-internet2** [comment]
I adjusted it to 5890-5899 so it uses ten ports instead of eleven.

We also need to adjust BWCTL not to use that range and the docs accordingly.

**Comment by bltierney** [comment]
merging with issue #22
