### ISSUE TITLE
Remove mention of Ubuntu 12.04

### ISSUE THREAD

**Issue by tonin** [perfsonar/docs#48]
Ubuntu 12.04 LTS reaches End of Life on April 28th 2017.  It is probably better not to release perfSONAR packages for this distro nor support it with our 4.0 release.

If we decide this, we should remove all mention of Ubuntu 12.04 LTS from the documentation and the website.

**Comment by schevali** [comment]
for Slidedecks and the Web

**Comment by szymontrocha** [comment]
There is not mention of Ubuntu 12 in the website.
What's the decision on the release?

**Comment by tonin** [comment]
@szymontrocha  We have decided to not support Ubuntu 12 in the 4.0 release.

**Comment by bltierney** [comment]
done.
