### ISSUE TITLE
Add pS to other tools comparison

### ISSUE THREAD

**Issue by szymontrocha** [perfsonar/docs#5]
During the GEANT project review it was clear that some of the reviewers had difficulties in uderstanding (or missing knowledge) about main differences between perfSONAR and other performance monitoring tools like RIPE Atlas or SamKnows. It's proposed to add some kind of comparison table in FAQ in order to try highlighting main points in key areas.

**Comment by tonin** [comment]
Maybe we can start to build a list here.  I'm dropping a few first things:

RIPE Atlas Probes
-------------------------
- Don’t do intrusive tests (no available bandwidth measurement)
- Can’t do measurement from your box only, you have to do measurements from a domain (AS), or a country

SamKnows
---------------
- Target broadband endusers
- Centralised scheduling of the tests by SamKnows
- Service specific tests (DNS, video, ftp, email, ...) or UDP tests only (no pure TCP) (see https://www.samknows.com/tests-and-metrics )

perfSONAR advantages
-------------------------------
- target campus/NREN networks
   - big pipes (1Gb to multiple Gb links)
- measurement mesh
- you control the measurements that run to/from your box
- better measurement accuracy when good hardware (better NIC and accurate NTP sync)
- available for a wider range of appliances (requirement is to run CentOS or Debian)

**Comment by szymontrocha** [comment]
I would propose we write it in the way what tools can do instead of what can't do :-) I think it sounds better when one reads it. So for RIPE atlas list what it can do and simply do not list what it can't measure. Anyway yes, discuss it here before any publishing.

**Comment by szymontrocha** [comment]
I would propose to structure it as a table with rows indicating parameter or functionality. Then for each tool there would be description or number or whatever. This would allow to directly compare things and should be easier to read.

So for instance a few examples of rows:
- One sentence description
- Type of measurements (list types)
- User-defined measurements (yes, no)
- Type of distribution (hw, sw, hw+sw)
- Access to measurements (local, central service, etc)

**Comment by szymontrocha** [comment]
I was thinking about something similar to:

    | perfSONAR | RIPE Atlas | SamKnows
--- | ----- | ------------- | --------------
Description | Network measurement toolkit designed to provide federated coverage of network paths. It provides an interface that allows for the scheduling of measurements, storage of data and generate visualizations | Active measurement network from the RIPE NCC. It consists of measurement probes that run measurements in the RIPE Atlas system and report results to the central data collection components | Probes for the measuring end-user broadband performance (fixed-line and mobile). They execute a series of software tests over their broadband connection they are connected to. The results of these tests are reported securely up to hosted backend infrastructure.
Type of measurements | tbd | tbd | tbd
User-defined measurements | tbd | tbd | tbd
Type of distribution | software | hardware | software, hardware
Access to measurements | tbd | tbd | tbd

**Comment by szymontrocha** [comment]
What about such table? Ideas for other items which may be useful?
I'm not sure if pS on-deman measurements needs more addition than just yes

**Comment by tonin** [comment]
Very good first draft for this table!

Maybe we could add a row about the targets of the measurement, separated from the types?  BTW, does SK provides informations about the measurement targets?

I think the local/central difference about the measurement storage and access to archive could have a bit more to be said.  For Ripe and SK it is on their infrastructure/servers, where as for perfSONAR it is on the infrastructure of the people having deployed the tools, meaning closer and more control to it.  I'm not sure what words to use to correctly describe that.

Also for the distribution type, maybe add more information on the supported hardware or the versatility of the software?

**Comment by tonin** [comment]
BTW, perfSONAR also provides ping (bwping).  And there is also something different about perfSONAR in that we can choose the source of the measurement to be another pS node (i.e. not only choosing the target) if the access is granted of course.

We could also add https://ring.nlnog.net/ to the comparison?

**Comment by szymontrocha** [comment]
What do you mean by targets of the measurement?
OK for some more info.
I thought that syaing "user-defined measurements" was broad enough to include any type of tests just saying one can do this.
However generally I'm reluctant to add many details as well as long descriptions to any rows. I think the table should be a short overview with more general differences and not pretend to be extensive source of information for those who don't want to go into web pages reading :-) . Please note things may change in other tools in future so some review may be necessary in future.
Let me do next round and see.

**Comment by tonin** [comment]
By target of measurements I was trying to find a way to differentiate where the user had control on where the measurement are happening or if it was something the tool had decided itself.  For example:
- any pS host for perfSONAR
- predefined targets for RIPE Atlas (first and second hop, DNS root servers, ...)
- dynamic choice of other RIPE Atlas probes (one probe in one country or AS)
- not sure for SamKnows (the documentation doesn't tell)
- etc.

For example, with RIPE Atlas probes, I think you cannot ask your probe to do regular measurements to another probe of your choice.  I wanted the table to show this difference.

**Comment by vbajpai** [comment]
Perhaps this (below) helps? -

A Survey on Internet Performance Measurement Platforms and Related Standardization Efforts
IEEE Communications Surveys & Tutorials, April, 2015
http://vaibhavbajpai.com/documents/papers/proceedings/lsmp-comst-2015.pdf

**Comment by szymontrocha** [comment]
Thx for suggestion. I will have  alook at it before next version of the table

**Comment by szymontrocha** [comment]
I made another version. To be honest I would suggest to not to extend it furthermore as it's not intended to be a survey (like the doc) but a short comparison of pS to a few other known tools. Please let me know what you think and with corrections if you want to modify/correct and whether it's ok to put it in the pS page.

**Comment by szymontrocha** [comment]
Isn't 3.5 release a good time to publish it? Is this accepted by all or we still need to work on it taking into account my comments above?

**Comment by tonin** [comment]
Yes, I also think we should publish now for the 3.5 release.  Content of the table is fine for me.  Thanks!

**Comment by szymontrocha** [comment]
Question is where. To www.perfsonar.net (e.g. About section) or FAQ? It's more general then related to installation.

**Comment by arlake228** [comment]
You should send a note @JWZurawski about this (unless my mentioning him brings this to his attention first). It probably makes sense to put on the perfsonar.net web site somewhere.

**Comment by JWZurawski** [comment]
Correct - @JWZurawski filters *all* mail unless his name is mentioned :)

Send me whatever it is, and where it should live, and i will make it iso.

**Comment by szymontrocha** [comment]
Note sent to @JWZurawski

**Comment by szymontrocha** [comment]
@JWZurawski created the subpage:
http://www.perfsonar.net/about/comparison-with-other-monitoring/
I will put content there

**Comment by szymontrocha** [comment]
Finished
