### ISSUE TITLE
make sure manage_security.rst is up to date

### ISSUE THREAD

**Issue by bltierney** [perfsonar/docs#51]
Should probably refactor this page too, and put list of ports needed at the top.

**Comment by bltierney** [comment]
made a first pass, but needs to be reviewed, and make sure that it is in sync with what is actually in iptables.

**Comment by bltierney** [comment]
andy wants to readd text on how to add your own rules.

**Comment by arlake228** [comment]
Closing. the existing section that got added back after brian's initial edit is adequate: http://docs.perfsonar.net/manage_security.html#adding-your-own-firewall-rules
