### ISSUE TITLE
update http://www.perfsonar.net/deploy/security-considerations

### ISSUE THREAD

**Issue by bltierney** [perfsonar/docs#52]
This page is out of date.

Port usage section should be a link to docs.perfsonar.net/manage_security.html, which now includes this information.

**Comment by szymontrocha** [comment]
There is laso #32 I'm not sure from the changes in #32 if security_considerations should be left as it is now or removed totally. There is info there about ssh access, using pS with firewall and some statemenats about NTAC paper...

**Comment by bltierney** [comment]
I think maybe the stuff left at  http://www.perfsonar.net/deploy/security-considerations/  is still useful, and can be left as is. What do you think?

**Comment by bltierney** [comment]
needs review, and link to more info on adding iptables rules on the toolkit:
 http://docs.perfsonar.net/release_candidates/4.0rc3/manage_security.html
