### ISSUE TITLE
update graph documentation

### ISSUE THREAD

**Issue by bltierney** [perfsonar/docs#54]
http://docs.perfsonar.net/using_graphs.html needs to be updated for new graphs.

**Comment by szymontrocha** [comment]
I see this page updated but I think Michael is still working on some additional features. 
The repository is missing the last picture images/using_graphs_error_message.png

**Comment by apertome** [comment]
There is a much more updated version here:

http://docs.perfsonar.net/release_candidates/4.0rc3/using_graphs.html?highlight=graphs

I have been planning on updating it further, but if @szymontrocha would like to do it I would be happy to let him. Let me know.

**Comment by apertome** [comment]
I do see the missing image, I'll see if I have it.

**Comment by lisaens** [comment]
I made updates to the text and images and pushed changes to 4.0rc3.
Please review.

**Comment by szymontrocha** [comment]
Closed via b5ae8932177cb2a1d97cce57884618d4c439f63b
