### ISSUE TITLE
update FAQ page

### ISSUE THREAD

**Issue by bltierney** [perfsonar/docs#55]
http://www.perfsonar.net/about/faq/ should be migrated to docs.perfsonar.net, and updated.

**Comment by bltierney** [comment]
ready for Andy to make a pass removing obsolete items, then I'll finish it.

**Comment by bltierney** [comment]
Done with my pass. Others should review.

**Comment by arlake228** [comment]
I did a pass. I made a lot of changes on both the formatting and content side. Assigning back to Brian to decide if we need another pass or if we are good enough for 4.0.

**Comment by bltierney** [comment]
Jason: Do you want to look this over? Otherwise lets close it.

**Comment by JWZurawski** [comment]
Not anytime in the next 3 weeks - if you had people review its probably ok.
