### ISSUE TITLE
update https://www.perfsonar.net/deploy/hardware-selection/deployment-examples/

### ISSUE THREAD

**Issue by bltierney** [perfsonar/docs#56]
Verify that this page is up to date. Or just remove it?
I'm not sure it makes sense for this page to be here at all.

**Comment by schevali** [comment]
Does it make sense to add the small nodes testbed suggestions to this example deployment page?

**Comment by bltierney** [comment]
maybe, but I think it should be on docs.perfsonar.net, not www.

I want to only have very static stuff on www.

**Comment by szymontrocha** [comment]
I moved the content from www to docs (73517ee9271cd502f02f0848d8731e7922eedcec). In www this page is no longer visible (to be deleted when issue closed). In docs I created another section in the main page called Deployment Examples (f8db00209bd9db8a9f51ee15573ce927f3da9f53). This page however need reviewing as I don't know how much current examples are.

**Comment by bltierney** [comment]
I updated the ESnet section; Matt should update Internet2 section; GEANT section should be added?

**Comment by tonin** [comment]
@igarny & @szymontrocha Can you coordinate so to add some recommendations under a new GÉANT section?  Either with what is deployed in the GÉANT backbone or with what is deployed in some other networks like PIONIER or DFN?

**Comment by szymontrocha** [comment]
Just for clarification, the page is now at http://docs.perfsonar.net/release_candidates/4.0rc3/deployment_examples.html. I will add GEANT low cost setup.

**Comment by szymontrocha** [comment]
Added GEANT low cost project example with ede500effa71d24c42a8e7e4f2f055c153319a5e

**Comment by mattzekauskas** [comment]
Matt still working on Internet2 section, will add something about the ad-hoc nodes (which hopefully will be updated in the near future!)

**Comment by schevali** [comment]
Current examples are looking good and I continue to work on a small nodes review of the INIU testbed models (without making it super long - currently distilling).  Linked to this page from the more condensed  install_small_node_details page.

**Comment by szymontrocha** [comment]
@schevali - are we ready to close it? I think we don't have to keep it open. In case some specific additions are needed we can open a new more specific ticket.
