### ISSUE TITLE
Document graphical installation for NetInstall and FullInstall

### ISSUE THREAD

**Issue by arlake228** [perfsonar/docs#6]
Both the full install and netinstall support a graphical installation method. We should document this with screenshots and text as the main Step-by-Step guide since it is the new default. The current content can be moved to a separate section in the same document on the text install.

**Comment by szymontrocha** [comment]
I'm starting to work on it. I will make two subsections in each "Install Guide".

**Comment by szymontrocha** [comment]
Fullinstal part done in e30bbc91bdd1ed9a462f35812c418b17b77cc1ae

**Comment by szymontrocha** [comment]
Andy, you may generate htmls

**Comment by arlake228** [comment]
Done. It's looking very good.

**Comment by szymontrocha** [comment]
Netinstall partially done in 7a74f637cc8c0aa6108bbd4bcc36cc29a6c63da6
As I'm not able to use the Netinstall type of installation in my VM I so far only reformatted the page to include two types of installation (graph and text). Graphical part would need screenshots (all with install_netinstall-graph*.png ) and reviewing the flow of screens. Text part should be fine as screens didn't change and can be reused for both installs.

**Comment by arlake228** [comment]
I can do the screenshots for the NetInstall. I'll try to have them today.
