### ISSUE TITLE
Consolidate system requirements discussion

### ISSUE THREAD

**Issue by arlake228** [perfsonar/docs#60]
Currently there are at least 4 pages on docs.perfsonar.net that talk about system requirements:

http://docs.perfsonar.net/release_candidates/4.0rc3/install_hardware.html
http://docs.perfsonar.net/release_candidates/4.0rc3/install_hardware_details.html
http://docs.perfsonar.net/release_candidates/4.0rc3/install_options.html#system-requirements
http://docs.perfsonar.net/release_candidates/4.0rc3/install_sys_requirements.html

We need to consolidate these or we are inevitably going to miss one of these in an update and have conflicting information. Assigning to self to see where consolidation can occur.

**Comment by szymontrocha** [comment]
There is also other pages with hw requirements for small nodes which section should be moved to a master requirements page:
http://docs.perfsonar.net/release_candidates/4.0rc3/install_small_node_details.html
To me this could be just three pages for simplicity under main page section **Planning for Installation** which I created:

**Hardware considerations** (use http://docs.perfsonar.net/release_candidates/4.0rc3/install_hardware.html and add data from http://docs.perfsonar.net/release_candidates/4.0rc3/install_hardware_details.html, remove section about low cost hw but refer to http://docs.perfsonar.net/release_candidates/4.0rc3/install_small_node_details.html)
**Supported operating systems** (create a new page install_system to contain just OS requirements from http://docs.perfsonar.net/release_candidates/4.0rc3/install_options.html#system-requirements)
**Recommendations for perfSONAR on Low-cost Hardware** (http://docs.perfsonar.net/release_candidates/4.0rc3/install_small_node_details.html, change title)

Remove any other text in docs about sw or hw requirements and put reference to above pages.
In addition to Andy's list there are also:
http://docs.perfsonar.net/release_candidates/4.0rc3/install_centos.html
http://docs.perfsonar.net/release_candidates/4.0rc3/install_debian.html

**Comment by schevali** [comment]
2 hardware pages. (install_hardware.html and install_small_node_details.html)

OS data on the install_centos/debian pages.

Brian suggests link-off pages for hardware examples (the supermicro specs from low-cost page)

Small node comments: no MA's, ...

Remove from install_options:
"System Requirements¶
Operating System:
Any system running CentOS 7. perfSONAR toolkit ISOs are only available as CentOS 7. CentOS 7 drops support for i386/i686 architectures and as a result there are only x86_64 versions of the CentOS 7 perfSONAR packages available.
We still offer packages support for any system running either a 32-bit or 64-bit CentOS 6. Existing CentOS 6 users will be able to auto-update.
Other RedHat-based operating systems may work, but are not officially supported at this time.
Any system running either a 32-bit, 64-bit or ARM Debian 8, or Ubuntu 14 is currently supported for the perfsonar-testpoint bundle. Other Debian flavors derived from Debian 8 such as Ubuntu 14 should work too but are not officially supported.
Hardware:
Most modern systems should be adequate to run the perfsonar-tools, perfsonar-testpoint and perfsonar-core bundles. We recommend at least 2GB of RAM and 20GB of disk space.
For running a measurement archive, you should have at least 4GB of RAM, and 50GB of disk.
You may want a 10Gbps network interface card depending on the throughput testing you wish to perform.
See the fasterdata.es.net hardware page for suggested configurations."

**Comment by bltierney** [comment]
I think this is done, so closing. Feel free to reopen (or start new issue) if something remains to be done.
