### ISSUE TITLE
Get rid of out-of-context static references to version numbers

### ISSUE THREAD

**Issue by arlake228** [perfsonar/docs#61]
There are a number of references to very specific version numbers that are completely out of context, like perfSONAR 4.0. By "out-of-context" I mean if we were to release 4.1 tomorrow we'd have to go update them because they reference nothing specific to 4.0. A main goal of using this platform when we switched to it, is to avoid problems like this. If every update I have to grep for the version number, something is wrong. It's ok to reference a specific version number when say you're pointing out when a feature was added. A statement like "Support for pScheduler was added in perfSONAR 4.0" will still be true 10 releases from now but things like "Here is how you troubleshoot perfSONAR 4.0" when you could just say "perfSONAR" is not ok. 

This issue is to go through and delete the references like that.

**Comment by bltierney** [comment]
I did some of this. Need to check if any remain.

**Comment by bltierney** [comment]
finished this.
