### ISSUE TITLE
misc edits/suggestions from Lisa Ensman, IU

### ISSUE THREAD

**Issue by bltierney** [perfsonar/docs#63]
Install Options - 
 http://docs.perfsonar.net/release_candidates/4.0rc3/install_options.html
	Say the CentOS Toolkit ISO includes the following “bundles",
	and use the term "bundle" in 2 to 5 also (eg, "This bundle includes..."), just to make it even more clear that if you want one of those, "CentOS Bundle Installation" is what you want to click below.  (Might as well make it even more obvious.) 

Installation on CentOS -
http://docs.perfsonar.net/release_candidates/4.0rc3/install_centos.html
	Instead of "Toolkit distribution", always say "Toolkit ISO" or "Perfsonar-toolkit bundle". Use consistent naming so it's always clear which you're talking about.  Also use "bundle" and "package" consistently.

	Put "You will need to follow the steps below as a privileged user" in bold.

	Step 2 - Make the title "Install a Bundle ". Add a small paragraph saying to "choose one of the following and see the Install Options  page for more info about what these bundles are". (It's not clear whether these are options or steps.)  Add that the Central Management bundle  is the only one that might be installed alongside another bundle.
	
	Step 3 - Can both NTP and System tuning be ignored for perfsonar-toolkit package?
	Should it be  "If an optional package was installed"?  

	Step 4 -  typo: firewalld
	Say which bundles include the security package. 

	Step 5 -  Should say that auto-updates is on by default (and what it does), and to disable it, 
	run "systemctl stop yum-cron".  Might be good to also say how to check whether it's on or not.

	Step 6 - Typo: should be no comma after "automatically. "
	Would be good to say how to check to see if service_watcher is on or not. 

	Step 7 - Typo: missing t in the in the 1st sentence. Reword:  "This step can be done through the web
	interface if the persfsonar-toolkit bundle (or the ISO) was installed (see step 9)." 
	
	Step 8 - Instructions should say to check to see if the services are running using
		systemctl status bwctl-server  
		systemctl status pscheduler-scheduler.service 
		systemctl status owamp-server.service 
		systemctl status perfsonar-lsregistrationdaemon.service
	After installing perfsonar-toolkit, they were already running for me. Maybe with other bundles, they would not be running, so say how to start them by rebooting or by commands. Are the init.d commands correct???  What would happen if your clocks weren't synched yet? How would you know when they became synched?

	Step 9 - Configuring should be another numbered step (?).  
		Configuring Central Management - say to do this only if you downloaded that bundle.  
		Say Configuring PerfSonar through the web interface (?). Repeat that this applies if you installed the Template-toolkit bundle (or the ISO). 
		The selinux stuff is not needed anymore. The echo command didn't work for me. I skipped it all.

Configuring the Toolkit for the First Time - 
http://docs.perfsonar.net/release_candidates/4.0rc3/install_config_first_time.html
	Your first login - the stuff about getting a prompt is only for ISO installs.  Make a title to indicate this and give instructions for other situations as well.
	Eg, If you had a host set up already, you just need to create a web interface admin user and consider disabling ssh access.
	To create a web user:
		Type /usr/lib/perfsonar/scripts/nptoolkit-configure.py.  
		You will be able to choose to Change Timezone, Manage users, or exit.
		Choose 2.   Then choose to Add a new user (1).  Save username and password.
		Exit out.

	Accessing the Web Interface -  Put the "(A)" and "(B)" at the ends of the description of the locations, ie 
	"... of the main page (A) or on the Configuration button ... corner (B)". 
	
	Give a link to the Global Services directory.
	
	Updating Your Admin Info - Say you'll be asked to login with the username and pw you just created the first time you go to Configuration page.

**Comment by szymontrocha** [comment]
Updated changes to install_centos.rst with e0c38d4ebb58086e2375bf55142e84f1c0132631

**Comment by szymontrocha** [comment]
Updated changes to install_config_first_time.rst with a4cf29175039df47600f42100bd8e4609dbf95cf

**Comment by szymontrocha** [comment]
Closed via 692d6fcb968db91e578a863d654374148b655758
