### ISSUE TITLE
Clean up the main menu

### ISSUE THREAD

**Issue by szymontrocha** [perfsonar/docs#64]
I think the left side menu of http://docs.perfsonar.net/release_candidates/4.0rc3/index.html needs some restructuring. Now everything is under a single big main section "perfSONAR User Guide" with just another one called for some reason "Next topic" where we just have "What is perfSONAR?". It's probably wise to put more structure of main items into it and rename the last one.

**Comment by szymontrocha** [comment]
Thinking longer about it, it just may be how the menu is designed/presented in the system (one big item in the beginning which smaller items of the same font size below) and not done by us. We may discuss it in the call if it's something to change.

**Comment by arlake228** [comment]
All of that is auto-generated and based on the headings in the body of that doc. Personally I have no issue with the headings themselves or that menu at the moment. if we think we need to tweak fonts sizes or other style things, that can be done in CSS.

**Comment by szymontrocha** [comment]
Understood. It's just my view. I found it a bit strange why the last secion is called "Next topic" and contains just one item "What is perfSONAR?". But you can close this probably as not much important.

**Comment by schevali** [comment]
Super-low priority for future thought (modifying underlying left-nav)
