### ISSUE TITLE
Review install_centos page

### ISSUE THREAD

**Issue by arlake228** [perfsonar/docs#68]
I was looking at this page and it needs some clean-up. I did a little bit of initial work to get stuff that was blatantly wrong off of it, but it needs someone with expertise on our packaging to go through and fix it up. In particular most steps after step 2 require the optional packages to be installed, but they are not very clear about that fact. Need to do some consolidation of those steps as well to make it clearer. They make something really easy look really complex as is.

**Comment by schevali** [comment]
Rebuilding some machines from current production and will follow the page here directly and update as holes are discovered/updates are needed.

**Comment by szymontrocha** [comment]
I went through the page with reall installation and it seems to be working fine. Andy made changes earlier to the page. I think we can close it now.
