### ISSUE TITLE
perfSONAR YouTube channel improvements

### ISSUE THREAD

**Issue by szymontrocha** [perfsonar/docs#72]
Would be good to improve this account view a bit:

- [x] Change graphics with logo with graphics of better size (to fit the whole banner, now part is grey)
- [x] Add description and pS links in About section/window

**Comment by schevali** [comment]
Collect most current/good videos into the channel?

**Comment by schevali** [comment]
Created by Luke. Who else should have edit rights?

**Comment by szymontrocha** [comment]
Luke was so kind to convert the account as a BrandAccount so that now user management can be done. And I was assigned editor rights. 
I added logo and graphics and also description.
Now I'm workind on adding Polish subtitles and will also review English ones

**Comment by szymontrocha** [comment]
Will close it as all items are adone but open separate for subtitles adding
