### ISSUE TITLE
work with NSRC to update their perfSONAR training videos

### ISSUE THREAD

**Issue by bltierney** [perfsonar/docs#73]
A number of these videos need to be updated for 4.0:

https://learn.nsrc.org/perfsonar

Some of this can be fixed just by sending new screen captures, and they can edit them in using the existing voiceover.

The NSRC contact for this is: Andrew Kirkpatrick <andrewn@uoregon.edu>

**Comment by schevali** [comment]
Brian's had good experience working with QuickTime .mov for shipping off to NSRC.

**Comment by schevali** [comment]
Legend:
Timestamps highlighted in gray denote a minor issue which can be easily swapped and/or potentially ignored altogether
Timestamps highlighted in yellow denote an issue which should be addressed, but can probably be easily swapped through replacement of images (no voice-over changes)
Timestamps highlighted in red denote a major change which will likely involve re-recording of voice and video


Intro and Installation:
-	What is perfSONAR
o	2:17 – 2:23 – Old graph example; could remain, but might be better to show the newer design for familiarity
o	3:50 – End credits, include University of Michigan logo?
-	perfSONAR Deployment Plan
o	3:01 – End credits, include University of Michigan logo throughout?
-	How to select hardware for perfSONAR
o	1:24 – 1:56 – Old graph example (NTP drift) – could be fine as is, simple diagram of clock drift on a VM
o	3:19 – End credits
-	Install perfSONAR
o	0:55 – 1:43 – Old website seen (Dec 2015)
	Video shows two clicks to get to content. Inclusion of pS bundles complicates the selection process and now leads to a selection matrix for choosing the desired software:
http://www.perfsonar.net/ (click “Download”)
http://www.perfsonar.net/about/where-can-it-be-downloaded/ (click “Downloading perfSONAR”)
http://www.perfsonar.net/about/where-can-it-be-downloaded/#Downloading_perfSONAR (page anchor link; click “installation options section”)
http://docs.perfsonar.net/install_options.html (review the decision matrix and select version/bundle at bottom of the page; from Toolkit ISO to package installations via yum or apt-get depending)
•	http://docs.perfsonar.net/install_getting.html ISO toolkit download
•	http://docs.perfsonar.net/install_centos.html package installation on CentOS
•	http://docs.perfsonar.net/install_debian.html package installation on Debian/Ubuntu
o	1:55 – 2:16 CentOS 6 version shown. Should be acceptable still unless we wish to normalize CentOS 7 visually
o	2:16 – 3:08 CentOS 6 installation process beginning continues – visuals here are significantly different than that of CentOS 7, but again not necessarily a deal breaker?
o	3:23 – 4:48 CentOS 6 initial setup choices shown. Audio throughout is fine if the timing can be synched to Jason speaking
o	4:49 – End credits
-	Secure a perfSONAR Node
o	4:21 – End credits
-	Interpreting Performance Behind Firewalls
o	1:07 – 1:52 – Old throughput graph demonstrating firewall degradation of throughput; still completely usable, just outdated visually
o	5:12 – End credits
-	Understanding TCP Buffer-Size
o	1:52 – End credits

Configuration
-	How to Configure the Toolkit
o	0:39 – 4:05 – Older Toolkit web admin area; replace?
o	4:05 – End credits
-	How to Configure Enabled Services
o	0:25 – 3:42 – Outdated Toolkit web administration displayed; inclusion of BWCTL client as an enabled source; recommend replacement
	Jason’s audio here is also going to need to be reworked/replaced as BWCTL and NDT are both explained and discussed
o	3:43 – End credits
-	How to configure NTP Services
o	1:09 – 3:20 – Outdated Toolkit web administration displayed; NTP settings significantly different on 4.0 toolkit
o	3:52 – 3-53 – Outdated Toolkit web administration displayed
o	3:54 – End Credits
-	How to Configure Testing Policies
o	0:35 – BWCTL daemon mentioned for setting testing policy; This is now handled via limits.conf - /etc/bwctld/bwctld.limits no longer part of pS 4.0
	Language of the file contents remains very similar, however getting to the limitation settings is in need of change which may necessitate a full remake of this episode.
o	5:57 – End Credits
-	Find Other perfSONAR Nodes
o	2:32 – End credits

**Comment by szymontrocha** [comment]
6 videos were updated and published:

1. Install perfSONAR
2. How to configure NTP services
3. How to find other perfSONAR nodes
4. Configure perfSONAR tools
5. perfSONAR graphing tools
6. pScheduler

**Comment by szymontrocha** [comment]
This was done in fact.
