### ISSUE TITLE
perfSONAR .pptx Template Check and Update

### ISSUE THREAD

**Issue by schevali** [perfsonar/docs#76]
http://www.perfsonar.net/about/training-materials/201604-ps-training/

**Comment by mattzekauskas** [comment]
Eric had a template done, Scott modified it to be a bit more compact on the bottom.  Matt will work with Scott to ensure it's uploaded correctly.

**Comment by schevali** [comment]
Completed and distributed to group, posted on http://www.perfsonar.net/about/training-materials/2017-07-ps-training/

**Comment by schevali** [comment]
All materials imported into new template.

**Comment by szymontrocha** [comment]
I crrected the footer date in v10
