### ISSUE TITLE
Introduction and Motivation Check and Update

### ISSUE THREAD

**Issue by schevali** [perfsonar/docs#77]
http://www.perfsonar.net/about/training-materials/2017-07-ps-training/

**Comment by schevali** [comment]
Completed conversion to new template and updated for 4.X. Ready for review.

https://drive.google.com/open?id=0Bx03S-N4ICZbVlRUS1RFM0E2d2M

**Comment by szymontrocha** [comment]
I reviewed it and updated a bit:
- consistent formatting, footer correction
- updated screenshots with latest versions
- added YT to resources
May need deployment graph update, provided newest version exists.
It's under 201709-perfSONAR-1-Intro_and_Motivation-v2.pptx in working directory

**Comment by szymontrocha** [comment]
I think there is no harm in publishing this one so I added to website. Otherwise we'll never finish it in Sep.
