### ISSUE TITLE
Hardware Selection Check and Update

### ISSUE THREAD

**Issue by schevali** [perfsonar/docs#79]
http://www.perfsonar.net/about/training-materials/2017-07-ps-training/

**Comment by schevali** [comment]
Content checked/updated for 4.0. New template applied. Uploaded to www.perf. Ready for peer review.

https://drive.google.com/open?id=0Bx03S-N4ICZbLUxlNDdPUWVmUFU

**Comment by szymontrocha** [comment]
Reviewed, as usually corrected footers and some formatting.
Uploaded to the web

In fact with this set and some others there is a problem of real world examples screenshots (and possibly hosts descriptions) which were taken years ago (eg. in 2013) . They are still technically correct but do not appliy to current look and feel of pS latest version. However updating it would require setting similar scenarios and knowledge of environment (they come from ESnet hosts, some of them no longer exist). What I could do was I just added a note about such "old" examples.
This may be somehow resolved with more work when we do next edition e.g. with 4.2 version.
