### ISSUE TITLE
Low Cost Hardware Check and Update

### ISSUE THREAD

**Issue by schevali** [perfsonar/docs#80]
http://www.perfsonar.net/about/training-materials/2017-07-ps-training/

**Comment by schevali** [comment]
This one has been expanded and completed. Updating template on it from last use

**Comment by schevali** [comment]
Completed. Awaiting peer review.

https://drive.google.com/open?id=0Bx03S-N4ICZbRUlrUlJ0d0ZoVEE

**Comment by szymontrocha** [comment]
I reviewed it:
- corrected formatting and footers
- I changed filename to give number 10 to this part of slide deck (as there were a few of 9s in filenames) so now it corresponds to parts numbering in https://www.perfsonar.net/about/training-materials/ps-training/

I think this one can easily be published now as there is not much more to review here.

**Comment by szymontrocha** [comment]
I published this one

**Comment by szymontrocha** [comment]
closing
