### ISSUE TITLE
Installation and Basic Configuration Check and Update

### ISSUE THREAD

**Issue by schevali** [perfsonar/docs#81]
http://www.perfsonar.net/about/training-materials/2017-17-ps-training/

**Comment by schevali** [comment]
This one has been updated and is going through template refresh from last use.

**Comment by schevali** [comment]
Completed. Awaiting peer review.

**Comment by szymontrocha** [comment]
I reviewed slides. Neds to be done:
- [ ] Correct pages numbering
- [ ] Worth mentioning at the beginning the reference sw version for the material
- [ ]  Screenshots in most of the pages must be replaced with new

I'm going to work on it.

**Comment by szymontrocha** [comment]
BTW I think the correct URL is http://www.perfsonar.net/about/training-materials/2017-07-ps-training/

**Comment by szymontrocha** [comment]
I finished editing this slide set. It's available here:
https://drive.google.com/open?id=0B1NNE6pjMJeAekQta0wwekZhVFE
201708-perfSONAR-2-Installation_and_Basic_Configuration-v3.pptx
There was a lot of work in fact:
- I replaced all screenshots with latest version
- I harmonized all slide look and feel (fonts, spacing, headers, etc) also modifying the template
- I corrected and harmonized footer

I think it looks good now.
For the final version to be put in web I suggest to remove version from filename and just leave date (if new slide deck is done it changes the date in fact).

**Comment by schevali** [comment]
Corrected spacing issues with images on the Web Admin sections. Otherwise looks good. Updated file in folder. Updating to the web.

**Comment by szymontrocha** [comment]
A bit too fast though. Please move the final version to https://drive.google.com/drive/folders/0B1NNE6pjMJeARWtlTmRPR0ZBTVU. There will a separate page in web as per #100 for reviewed material (September date)

**Comment by szymontrocha** [comment]
Slides uploaded to new page structure:
https://www.perfsonar.net/about/training-materials/ps-training/
In collaboration docs final versions are now in "pS 4.0 Training Materials - Final versions 201709 folder" under Training Materials.

**Comment by szymontrocha** [comment]
Closing
