### ISSUE TITLE
Deployment and Regular Testing Check and Update

### ISSUE THREAD

**Issue by schevali** [perfsonar/docs#82]
http://www.perfsonar.net/about/training-materials/2017-07-ps-training/

**Comment by schevali** [comment]
Suggestion: Include a slide on recommended distance of at least 20ms for meaningful testing of latency/throughput values. Include Do's/Don'ts image slides and reasoning.

**Comment by schevali** [comment]
Completed check/update to 4.0 material. Converted into new template. Uploaded to www.perf. Ready for peer review.

https://drive.google.com/open?id=0Bx03S-N4ICZbWlNCUHBVQzV6aVU

**Comment by szymontrocha** [comment]
I updated this one to correct all template issues, improve formatting (code sections), etc.
Updated version 201708-perfSONAR-3-Deployment_and_Regular_Testing-v3.pptx is in the training activity folder:
https://drive.google.com/open?id=0B1NNE6pjMJeAY3JuZnAxWFBBVHc
Needs final review now.
Later on we would need to update file name to reflect proper date.

**Comment by szymontrocha** [comment]
Let's get this one done too. Published to the web.
