### ISSUE TITLE
Measurement Tools Check and Update

### ISSUE THREAD

**Issue by schevali** [perfsonar/docs#83]
http://www.perfsonar.net/about/training-materials/201604-ps-training/

**Comment by szymontrocha** [comment]
This one is more complicated to update as all CLI commands are executed in a specific created environment (between selected hosts with given latency, forcing bad performance, etc). This would require access to such infrastructure.

**Comment by schevali** [comment]
Specifically the nm-altered examples showing loss/degraded throughput examples between distant end-points in the new scheduler format. Slides 16-21 and 29-35, then there are non-nm-related examples on slides 40-43 needing updated from BWCTL to pScheduler.

**Comment by arlake228** [comment]
Ok, I didn't pick-up on the altered environment aspect of this when we talked, my bad. I have created a v3 that updated slides 40-43 with pScheduler examples. I will need to dig in more to see what to do about the others. Those are the production esnet measurement hosts so not sure I want to be messing with them in that way.

**Comment by szymontrocha** [comment]
This also depends on docs#51

**Comment by szymontrocha** [comment]
Reviewed, as usually some small corrections of formatting. Uploaded v4 to the web.
