### ISSUE TITLE
Use Cases Check and Update

### ISSUE THREAD

**Issue by schevali** [perfsonar/docs#85]
http://www.perfsonar.net/about/training-materials/2017-07-ps-training/

**Comment by schevali** [comment]
Update completed. Converted to new template. Uploaded to www.perf.

https://drive.google.com/open?id=0Bx03S-N4ICZbWE9jNzhjbFJpaDg

**Comment by szymontrocha** [comment]
Reviewed, as usually corrected footers, pictures and formatting.
Uploaded to the web.
