### ISSUE TITLE
Security and Node Maintenance Check and Update

### ISSUE THREAD

**Issue by schevali** [perfsonar/docs#86]
http://www.perfsonar.net/about/training-materials/201604-ps-training/

**Comment by szymontrocha** [comment]
Worth mentioning:
- new way of setting web access users (htpasswd)
- taking care of central archive free disk space (cassandra compacting case when disk is already full)

**Comment by szymontrocha** [comment]
This also depends on #51

**Comment by schevali** [comment]
John hates cartoons and thought this deck should be minimized.

Scott's going to take a pass at this document eliminating ANYTHING not perfSONAR (directly) related.

**Comment by szymontrocha** [comment]
I merged these items into #155
