### ISSUE TITLE
A couple regular testing notes to add

### ISSUE THREAD

**Issue by arlake228** [perfsonar/docs#9]
Our documentation should answer these:

1. It seems this is a "push" architecture, i.e. the perfsonar node which 
made a measurement connects to the central MA to store the results there.

What happens if the central MA goes down for a while, or the network to 
the central MA? Are the measurements lost, or are they buffered to be 
delivered later? Does this have any effect on the timing of subsequent 
measurements?

What if there are multiple MAs selected, but only one is down or 
unreachable?

2. If you have made manual changes to regular_testing.conf to point to a 
different MA (or multiple MAs), and you subsequently change test 
configurations through the GUI, does this leave your MA customisations 
alone?

**Comment by szymontrocha** [comment]
Should this go to FAQ?

**Comment by arlake228** [comment]
I'd rather put the answers directly in the documentation. I won't argue if someone creates an FAQ in addition, but someone reading the docs should not have to seek out an FAQ to get answers to these.
