### ISSUE TITLE
Verify all ports opened by default firewall are documented

### ISSUE THREAD

**Issue by arlake228** [perfsonar/docs#92]
We still leave the NDT ports open so we don't break NDT on old installs. Ivan noted this is not mentioned in the docs, we should probably do so. 546-547 in particular are DHCPv6. 843 is related to the flash version of NDT.

> I have reinstalled my RRZE Testbed server and have found some ports being opened with no 

> explanation on the pS documentation page:
>  
> -A perfSONAR -p udp -m state --state NEW -m udp --sport 547 --dport 546 -j ACCEPT
> -A perfSONAR -p tcp -m state --state NEW -m tcp --dport 8090 -j ACCEPT
> -A perfSONAR -p tcp -m state --state NEW -m tcp --dport 3001:3003 -j ACCEPT
> -A perfSONAR -p tcp -m state --state NEW -m tcp --dport 7123 -j ACCEPT
> -A perfSONAR -p tcp -m state --state NEW -m tcp --dport 843 -j ACCEPT
>  
> I can recognize some, but again my point is about the documentation here.
> I guess there are some, that are not related to pS at all: UDP 546-547, TCP 843 or am I missing something?

**Comment by szymontrocha** [comment]
This applies to http://docs.perfsonar.net/manage_security.html
