### ISSUE TITLE
Document pScheduler test limits

### ISSUE THREAD

**Issue by arlake228** [perfsonar/docs#93]
Now that throughput and latency have a more complete set of limits, we should document the limits available for each test somewhere.

**Comment by mfeit-internet2** [comment]
At some point, I'd like to have all of that information in the enumeration so we can just pull it out and generate something readable.

**Comment by mfeit-internet2** [comment]
I'm becoming inclined to deprecate the `test` limits and encourage the use of `jq` limits instead.  Those are much more flexible and a lot easier to decipher.

**Comment by mfeit-internet2** [comment]
Closing because this will be deprecated.
