### ISSUE TITLE
Add link to YouTube Channel

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/docs#94]
Add an announcement that we have a YouTube channel and a permanent link somewhere on the sidebar.

That link is: https://www.youtube.com/channel/UCjK-P49pAKK9hUrrNbbe0Sg

**Comment by szymontrocha** [comment]
So far I added YouTube section under http://www.perfsonar.net/about/training-materials/
Will add announcement if ack. 
We may consider adding a red button at the top of the page

**Comment by szymontrocha** [comment]
Announcment sent. Information about YT channel on the web will soon be a bit more separated as per #101
