### ISSUE TITLE
perfSONAR Webinar - what's coming for 4.1

### ISSUE THREAD

**Issue by szymontrocha** [perfsonar/docs#96]
I'm opening it as a record of activities.

Webinar on what to expect for perfSONAR 4.1 release.

Preliminary date will be Sep 22

**Comment by mfeit-internet2** [comment]
For that date, the subject should probably be what's coming in 4.0.2 (which is actually a lot) and what we anticipate in 4.1, which is 4-5 months later.

**Comment by szymontrocha** [comment]
Closing it as I think this was covered in webinar from github/training#4
