### ISSUE TITLE
Remove all mention of enable/disable services

### ISSUE THREAD

**Issue by tonin** [perfsonar/docs#99]
Following work on https://github.com/perfsonar/toolkit/issues/263#issuecomment-326610683 we need to remove the pages and informations related to the management of services.

This means removing this page completely http://docs.perfsonar.net/manage_services.html but also check if there are any mention of this else where.

**Comment by vvidic** [comment]
Dropped the ``manage_services`` page along with the images linked from there and updated the page index.

**Comment by tonin** [comment]
The change has gone in the live version of the docs, but I guess it is not that bad as this page was outdated anyway.

**Comment by vvidic** [comment]
On Mon, Sep 04, 2017 at 01:32:14PM +0000, Antoine Delvaux wrote:
> The change has gone in the live version of the docs, but I guess it is
> not that bad as this page was outdated anyway.

Ouch, should we revert and create a branch with the change?

-- 
Valentin Vidic
Computer Systems Engineer - Expert
Department of Computer Infrastructure and Services
Croatian Academic and Research Network - CARNet
Josipa Marohnica 5, HR-10000 Zagreb, Croatia
tel: +385 1 6661 714, fax. +385 1 6661 635
gsm: +385 91 2480 919
www.CARNet.hr
